### ISSUE TITLE
任务的答案与实际测试不一致

### ISSUE THREAD

**Issue by zoujunlucky** [javascript-tutorial/zh.javascript.info#1013]
‘’https://zh.javascript.info/task/function-in-if‘’这个链接中的任务，给出的答案是error，但是我实际测试发现是可以运行的，函数的声明可能和变量声明不一样，请核对一下

**Comment by leviding** [comment]
本教程在开始的章节说过，默认使用严格模式，你运行可以是因为使用的环境未开启严格模式。
