### ISSUE TITLE
Promise小节的第三个任务超链接给错

### ISSUE THREAD

**Issue by yonhung** [javascript-tutorial/zh.javascript.info#1018]
[Promise](https://zh.javascript.info/promise-basics)小节的第三个任务里，英文版是有原来的任务链接的，但中文版这里链接好像是未找到，出错了。

![屏幕截图 2022-02-25 121915](https://user-images.githubusercontent.com/53432984/155653404-b3075fce-012b-4e21-ae6d-833cbe73fe51.png)

**Comment by leviding** [comment]
Fixed in https://github.com/javascript-tutorial/zh.javascript.info/commit/1abfa97187853a54dc58535cdd93f1b87fc9bcde
