### ISSUE TITLE
Can not buy ebook know

### ISSUE THREAD

**Issue by leviding** [javascript-tutorial/zh.javascript.info#1038]
https://zh.javascript.info/ebook

This project needs to be submitted for review.
If you are the merchant and the owner of this project:
To get this project reviewed – please log directly onto your merchant account, click "My Projects" and click the "Submit for Review" button.
To load the contents of this widget for testing purposes – please log directly onto your merchant account and refresh this page. Alternatively you can use the API parameter evaluation described in the API documentation.

@iliakan

**Comment by iliakan** [comment]
Which payment method did you use?

**Comment by iliakan** [comment]
Thanks, I see the problem.

**Comment by leviding** [comment]
> 我们很抱歉。 由于技术困难，只有Stripe和Paypal在工作。 我们将在下周修复它。

很抱歉，由于技术问题，目前只能通过Stripe和Paypal两种方式进行付款。 我们将在下周恢复其他付款方式。

**Comment by iliakan** [comment]
Thanks, much better this way ;)
