### ISSUE TITLE
私有的和受保护的属性和方法一章 汉化不全

### ISSUE THREAD

**Issue by situ2001** [javascript-tutorial/zh.javascript.info#1043]
发现[这里](https://zh.javascript.info/private-protected-properties-methods#si-you-de-waterlimit)没有汉化

在对应的md文件，有
https://github.com/javascript-tutorial/zh.javascript.info/blob/2da27218e6110f2e8ba006a7077994962ff69a63/1-js/09-classes/04-private-protected-properties-methods/article.md?plain=1#L189

定位到https://github.com/javascript-tutorial/engine/blob/master/markit/locales/recent/zh.yml

发现虽然有一个一年前的[PR](https://github.com/javascript-tutorial/engine/pull/31)，但并没有被merge

搜索一遍zh.javascript.info，仅有这一处使用到了` [recent browser=none] `

应如何解决这个汉化问题？是等待[PR](https://github.com/javascript-tutorial/engine/pull/31)被merge

还是使用像下面一样的方法进行汉化

https://github.com/javascript-tutorial/zh.javascript.info/blob/c257f5c32961389807138712fd944cb8cc98156b/1-js/09-classes/01-class/article.md?plain=1#L294-L296

**Comment by songhn233** [comment]
Done.
