### ISSUE TITLE
垃圾回收章节翻译建议

### ISSUE THREAD

**Issue by SpiritSamllFire** [javascript-tutorial/zh.javascript.info#1065]
> 如果一个值可以通过引用或引用链从根访问任何其他值，则认为该值是可达的。

建议翻译为：如果一个值可以从根通过一个引用（或引用链）被访问到，则认为该值是可达的

> en: Any other value is considered reachable if it’s reachable from a root by a reference or by a chain of references.

**Comment by songhn233** [comment]
这里的话我觉得甚至可以就用 `引用链` 就行，一个引用其实也能理解为引用链

**Comment by SpiritSamllFire** [comment]
> 这里的话我觉得甚至可以就用 `引用链` 就行，一个引用其实也能理解为引用链

确实，这样更简洁易懂
