### ISSUE TITLE
Map and Set章节有错误

### ISSUE THREAD

**Issue by wazyaa** [javascript-tutorial/zh.javascript.info#1080]
https://zh.javascript.info/map-set#map-die-dai
map.keys()，map.values()，map.entries()返回的都是迭代器而不是可迭代对象

**Comment by leviding** [comment]
The keys() method returns a new [iterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators) object that contains the keys for each element in the Map object in insertion order. In this particular case, this iterator object is also an iterable, so a [for...of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) loop can be used.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/keys

**Comment by wazyaa** [comment]
迭代器对象和可迭代对象不一样

**Comment by wazyaa** [comment]
迭代器可以调用next方法可迭代对象不行，比如文本就是可迭代对象

**Comment by wazyaa** [comment]
文章中写的是可迭代对象而不是迭代器对象

**Comment by leviding** [comment]
> The keys() method returns a new [iterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators) object that contains the keys for each element in the Map object in insertion order. In this particular case, this iterator object is also an iterable, so a [for...of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) loop can be used.
> 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/keys

In this particular case, this iterator object is also an iterable.

即是迭代器，也是可迭代对象。

@wazyaa @songhn233
