### ISSUE TITLE
元素大小和滚动章节 clientWidth/Height部分的两个错误

### ISSUE THREAD

**Issue by MrFlyHouse** [javascript-tutorial/zh.javascript.info#1083]
在上图中，我们首先考虑 clientHeight。
这里没有水平滚动条，所以它恰好是 border 内的总和：CSS-width 200px 加上顶部和底部的 padding（2 * 20px），总计 240px。

这句话里，CSS-width应该是改为CSS-height；

练习“将小球置于区域（field）中心”里解答当中，“那么在中心的会是球的左上边缘，而不是整个球”对应的样式示例（“这是它将显示出来的效果”一处），应该是足球的左上角位于球场中心吧？（这一点我发现英文原版也是如此，但是前面的js代码我放到本地测试的时候，发现结果是足球的左上角位于球场中心）

**Comment by leviding** [comment]
非常感谢，已在 https://github.com/javascript-tutorial/zh.javascript.info/commit/0693ff9a690f18130aa0465095b66eba67373461 中修复
