### ISSUE TITLE
data types 里很多文章都写在代码栏里

### ISSUE THREAD

**Issue by xiangcaizi113** [javascript-tutorial/zh.javascript.info#1085]
正文和标题都在代码栏里，文章阅读起来太困难了

**Comment by leviding** [comment]
请问你指的是什么，能否截图标注一下

**Comment by xiangcaizi113** [comment]
![image](https://user-images.githubusercontent.com/76252476/182335479-05816c1b-10f9-4a22-a231-dff3c2acda70.png)
文章都写在代码段里，字体大小都一样 。阅读起来很困难
1-js/05-data-types/05-array-methods/article.md
1-js/05-data-types/07-map-set/article.md
暂时阅读到这两篇里格式错误

**Comment by leviding** [comment]
@xiangcaizi113 GitHub 上是源文件，阅读教程可以去网站 https://zh.javascript.info/
