### ISSUE TITLE
动态导入部分翻译有点小问题

### ISSUE THREAD

**Issue by zhanghuize-git** [javascript-tutorial/zh.javascript.info#1088]
<img width="958" alt="image" src="https://user-images.githubusercontent.com/56755115/184571860-f50ffa77-00cc-4927-846d-0a5d3cc49b67.png">
这块应该是： 可以像***  不知道我理解的是否正确

**Comment by leviding** [comment]
已修复 https://github.com/javascript-tutorial/zh.javascript.info/commit/ba6eefe44b771ffdd62d2cdd3c7ec7e73164f272 ，感谢 👍

**Comment by zhanghuize-git** [comment]
谢谢的应该是你们 幸苦啦
