### ISSUE TITLE
在浏览器中调试章节翻译纠正

### ISSUE THREAD

**Issue by GE-PrimeMinister** [javascript-tutorial/zh.javascript.info#1090]
> [“资源（Sources）”面板](https://zh.javascript.info/debugging-chrome#zi-yuan-sources-mian-ban)
> 选择 Sources（资源） 面板
> 资源（Sources）面板包含三个部分

`Sources`在chrome中被翻译为源代码而不是资源

**Comment by songhn233** [comment]
这个需要对齐吗😂

**Comment by leviding** [comment]
我理解资源应该更好，这里暂时不对齐吧，谢谢反馈。
