### ISSUE TITLE
文本重复：Cookie，document.cookie/samesite

### ISSUE THREAD

**Issue by bullshitking-99** [javascript-tutorial/zh.javascript.info#1096]
https://zh.javascript.info/cookie#shu-ru-cookiesamesite-xuan-xiang
---
### 最后一段
> 我们肯定可以将 samesite 与其他保护措施（例如 XSRF token）一起使用，例如 xsrf token，......
### 修改建议
> 我们肯定可以将 samesite 与其他保护措施（例如 XSRF token）一起使用，......

**Comment by songhn233** [comment]
可以的，有兴趣提个 PR 吗
