### ISSUE TITLE
正则章节的一处翻译问题

### ISSUE THREAD

**Issue by Serious54088** [javascript-tutorial/zh.javascript.info#1100]
[9-regular-expressions/...](https://zh.javascript.info/regexp-methods#strmatchregexp)

> If the regexp has flag g, then it returns an array of all matches as strings, without capturing groups and other details.  
如果 regexp 带有修饰符 g，则它将所有匹配项的数组以字符串的形式返回，而不包含捕获组和其它详细信息。

结合上下文，原文的大意是：如果 regexp 带g ，方法将会返回一个包含所有匹配项的数组，该数组的元素（即匹配项）是字符串形式的、不包含其他匹配信息（作为对比，不带g的匹配项是数组形式的，包含 index input 等其他匹配信息）。

两种情况的匹配项形式对比如下：

```javascript
> 'a b c'.match(/\w/);  //不带g
  ['a', index: 0, input: 'a b c', groups: undefined]

> 'a b c'.match(/\w/g);  //带g
  (3) ['a', 'b', 'c']
```

**Comment by songhn233** [comment]
> 如果 regexp 带有修饰符 g，则它将返回一个包含所有匹配项的数组，但不包含捕获组和其它详细信息。

这样如何

**Comment by Serious54088** [comment]
This is an automatic reply, confirming that your email was received. I will reply as soon as possible. Thank you!

**Comment by Serious54088** [comment]
> 

不晓得怎么翻译，我觉得可以吧

**Comment by leviding** [comment]
Solved in https://github.com/javascript-tutorial/zh.javascript.info/pull/1101
