### ISSUE TITLE
6.1函数绑定章节-任务：作为方法的绑定函数，答案有误

### ISSUE THREAD

**Issue by lilipanpan** [javascript-tutorial/zh.javascript.info#1106]
function f() {
  alert( this ); // ?
}
let user = {
  g: f.bind(null)
};
user.g();

function f内的this绑定的是[object Window]

**Comment by zhouzhaonan** [comment]
“本教程的所有例子都默认采用严格模式，除非特别指定（非常少）。”
见 https://zh.javascript.info/strict-mode

检查脚本文件是否为严格模式。

**Comment by songhn233** [comment]
本书所有代码均默认在严格模式下运行，所以完整代码为

```js
"use strict";

function f() {
  alert( this ); // ?
}

let user = {
  g: f.bind(null)
};

user.g();
```

所以输出为 null
