### ISSUE TITLE
6.3、变量作用域，闭包

### ISSUE THREAD

**Issue by liuyangaizhuerchong** [javascript-tutorial/zh.javascript.info#1108]
// if内的函数：
let phrase = "Hello";
if (true) {
  let user = "John";
  function sayHi() {
    alert(`${phrase}, ${user}`);
  }
}
sayHi();
// 答案：error。
// 函数 sayHi 是在 if 内声明的，所以它只存在于 if 中。外部是没有 sayHi 的。

在vscode中能正常输入：hello,John 。并没有出现 error

**Comment by zhouzhaonan** [comment]
“本教程的所有例子都默认采用严格模式，除非特别指定（非常少）。”
见 https://zh.javascript.info/strict-mode

检查脚本文件是否为严格模式。

**Comment by songhn233** [comment]
所有代码都默认在严格模式下运行，所以其实完整代码是

```js
"use strict";

let phrase = "Hello";

if (true) {
  let user = "John";

  function sayHi() {
    alert(`${phrase}, ${user}`);
  }
}

sayHi();
```
if 包含在块作用域内
