### ISSUE TITLE
代码与功能描述不匹配

### ISSUE THREAD

**Issue by gongzhaoman** [javascript-tutorial/zh.javascript.info#1109]
问题定位：JavaScript 基础篇的 “循环：while 和 for”一章节中的[跳出循环](https://github.com/javascript-tutorial/zh.javascript.info/blob/master/1-js/02-first-steps/13-while-for/article.md#%E8%B7%B3%E5%87%BA%E5%BE%AA%E7%8E%AF)
问题描述：
1. 当执行代码，在输入框中输入0，返回sum：0，程序结束。
2. 而文中对代码的描述是当输入不是数字时才循环终止，程序结束，但实际上0是数字，程序也结束了。描述与实际矛盾。

**Comment by songhn233** [comment]
这个描述确实有歧义, 先在 https://github.com/javascript-tutorial/en.javascript.info 处理

**Comment by leviding** [comment]
update upstream https://github.com/javascript-tutorial/en.javascript.info/pull/3281

**Comment by leviding** [comment]
<img width="1463" alt="image" src="https://github.com/javascript-tutorial/zh.javascript.info/assets/26959437/08e28c5d-99e5-450d-b8ea-92f26fa6a6ab">
