### ISSUE TITLE
元素大小和滚动 CSS-positioned 缺少 sticky

### ISSUE THREAD

**Issue by Grapedge** [javascript-tutorial/zh.javascript.info#1114]
文档地址：https://zh.javascript.info/size-and-scroll#offsetparentoffsetlefttop

原文：
> 1. CSS-positioned (position is absolute, relative, fixed or sticky), or

译文：

> 1. CSS 定位的（position 为 absolute，relative 或 fixed），

positioned 元素缺少了 `sticky`。

**Comment by leviding** [comment]
Thanks, fixed in https://github.com/javascript-tutorial/zh.javascript.info/commit/486a1962becd88d39d3b83367deecf67cf986dbd.
