### ISSUE TITLE
Upstream update: Unicode, String internals

### ISSUE THREAD

**Issue by situ2001** [javascript-tutorial/zh.javascript.info#1124]
I noticed that there is a new article [Unicode, String internals](https://javascript.info/unicode) created at the upstream.
When is the next sync to upstream?
I would like to translate this article.

Thanks.

**Comment by leviding** [comment]
Thanks, I will sync it and mention you in this weekend.

**Comment by leviding** [comment]
Hello @situ2001 

New article has been created, you can create a new branch to translate it, and make a pull request when the translation is done.

**Comment by situ2001** [comment]
Okay, I will translate it tomorrow morning.
