### ISSUE TITLE
在算术函数和表达式中，会自动进行 number 类型转换。 

### ISSUE THREAD

**Issue by Qiushuangjia** [javascript-tutorial/zh.javascript.info#1126]
基础知识-类型转换-数字型转换
问题定位： 
在算术函数和表达式中，会自动进行 number 类型转换。
比如，当把除法 / 用于非 number 类型
问题描述:
做加法算术的时候， 两边有一个是字符串类型时, + 应该为字符串连接符吧， 并不会进行 number 转换 。

**Comment by leviding** [comment]
> 基础知识-类型转换-数字型转换 问题定位： 在算术函数和表达式中，会自动进行 number 类型转换。 比如，当把除法 / 用于非 number 类型 问题描述: 做加法算术的时候， 两边有一个是字符串类型时, + 应该为字符串连接符吧， 并不会进行 number 转换 。

这篇文章在这里是做的一个笼统的介绍，而且以除法为示例。为了由浅入深，你所指出的这个情况会在下一节介绍。在文中有指出。

![image](https://user-images.githubusercontent.com/26959437/199538339-4b70746c-5560-4a35-ade3-732e633f18e3.png)
![image](https://user-images.githubusercontent.com/26959437/199538395-3019d496-4cd2-46bd-b2ae-7b24cdc27a31.png)

> 大多数数学运算符都执行这种转换，我们将在下一节中进行介绍。

**Comment by leviding** [comment]
@Qiushuangjia 感谢提出疑问，如果我的回答没能解决你指出的问题，请重新打开此 issue，我们继续探讨
