### ISSUE TITLE
文本订正

### ISSUE THREAD

**Issue by dongshian** [javascript-tutorial/zh.javascript.info#1127]
#### path: /master/1-js/08-prototypes/04-prototype-methods/article.md
![image](https://user-images.githubusercontent.com/29789455/200252250-a019c5a5-a43b-47ef-ad60-5b606363739e.png)

**Comment by leviding** [comment]
感谢，已修复 https://github.com/javascript-tutorial/zh.javascript.info/commit/216beb6ddc8a9180982820fb9204b5fbc530ddff
