### ISSUE TITLE
函数表达式

### ISSUE THREAD

**Issue by XuChongmin** [javascript-tutorial/zh.javascript.info#1130]
如下代码是函数表达式中的例子 ：
问题描述：在js现代教程页面中的确是按照预期的方向执行
出现的问题描述：自己使用编译工具vscode1.73.1版本，环境为谷歌浏览器v8，可以正常执行，无报错。
let age = prompt("What is your age?", 18);

// 有条件地声明一个函数
if (age < 18) {

  function welcome() {
    alert("Hello!");
  }

} else {

  function welcome() {
    alert("Greetings!");
  }

}

// ……稍后使用
welcome(); // Error: welcome is not defined

**Comment by leviding** [comment]
本教程在最初的几个章节说过，默认启用严格模式，遵循现代的 JavaScript 规范。

浏览器默认是未开启严格模式的。

当如下图手动开启严格模式，即可得到教程说述的效果：

<img width="441" alt="image" src="https://user-images.githubusercontent.com/26959437/204096723-0df90e3c-5e03-4b5c-8a97-0476d3c10de9.png">
