### ISSUE TITLE
正则表达式-捕获组章节代码错误

### ISSUE THREAD

**Issue by MrFlyHouse** [javascript-tutorial/zh.javascript.info#1138]
https://zh.javascript.info/regexp-groups#shi-li-gogogo
捕获组-示例中的代码，中文版写为
```js
alert( 'Gogogo now!'.match(/(go)+/i) ); // "Gogogo"
```
但是实际输出情况为Gogogo,go

参考英文原文
https://javascript.info/regexp-groups#example-gogogo
实际上实例中的代码是
```js
alert( 'Gogogo now!'.match(/(go)+/ig) ); // "Gogogo"
```
增加了全局匹配，所以才得到了注释中的输出
还请修改

**Comment by songhn233** [comment]
Will close by https://github.com/javascript-tutorial/zh.javascript.info/pull/1139.
