### ISSUE TITLE
代码描述与运行结果不相符

### ISSUE THREAD

**Issue by chenchenbaobao** [javascript-tutorial/zh.javascript.info#1140]
Object 基础知识 4.4 对象方法this 中的任务 在对象字面量中使用this  解决方案说他是一个错误
然而他并不是一个错误，他是一个空值 实际上 这个name是winodw.name
根据下面的一些描述 是不是指的是在严格模式下 但是代码里面没有体现
<img width="781" alt="截屏2023-01-31 11 02 39" src="https://user-images.githubusercontent.com/88490404/215652262-d33af36e-766d-4b8d-b290-ff4916782df0.png">

**Comment by leviding** [comment]
<img width="873" alt="image" src="https://user-images.githubusercontent.com/26959437/215821587-ceea8cfa-5568-4841-abb1-33fdde5dfdc9.png">

https://zh.javascript.info/strict-mode#wo-men-ying-gai-shi-yong-usestrict-ma
