### ISSUE TITLE
代码中，注释有误

### ISSUE THREAD

**Issue by OverTheMountains** [javascript-tutorial/zh.javascript.info#1146]
问题定位：二进制数据，文件：Blob  文章内 [Blob 转换为 ArrayBuffer](https://zh.javascript.info/blob#blob-zhuan-huan-wei-arraybuffer)

问题描述：

代码里注释部分  
// 从 bolb 获取 arrayBuffer
Blob 拼写错误。

**Comment by leviding** [comment]
solved https://github.com/javascript-tutorial/zh.javascript.info/issues/1146
