### ISSUE TITLE
Bad gateway 502. The web server reported a bad gateway error.

### ISSUE THREAD

**Issue by leviding** [javascript-tutorial/zh.javascript.info#1147]
![image](https://user-images.githubusercontent.com/26959437/228210559-85cd1699-07db-4c79-8e90-851eb3c31bd6.png)

@iliakan

**Comment by yangzi0210** [comment]
我也是这个问题今天

**Comment by Leonard-Liu19** [comment]
我也遇到了，一直打不开页面😭

**Comment by Leonard-Liu19** [comment]
> 我也遇到了，一直打不开页面😭

我的这个问题已经没了，可以正常打开了，不过不知道具体原因
