### ISSUE TITLE
中文教程有错误

### ISSUE THREAD

**Issue by ztw1002** [javascript-tutorial/zh.javascript.info#1149]
https://zh.javascript.info/javascript-specials
![image](https://user-images.githubusercontent.com/44706242/231934245-a479b96a-7b32-4d94-a1f6-5ef6ded3fff1.png)
这里中括号的位置不对

**Comment by freemedom** [comment]
这样写似乎是对的？英文版不对

**Comment by leviding** [comment]
这样写是表示逗号也是选填的，谢谢提问。
