### ISSUE TITLE
2.8节的逗号运算符

### ISSUE THREAD

**Issue by huashen84** [javascript-tutorial/zh.javascript.info#1158]
原文：逗号运算符能让我们处理多个语句，使用 , 将它们分开。每个语句都运行了，但是只有最后的语句的结果会被返回。

逗号运算符应该是分割表达式？

**Comment by songhn233** [comment]
Hello，首先原文中是 comma operator，直译即为逗号运算符，同时常见翻译中都会采取这种说法，图为中文维基百科。

![image](https://github.com/javascript-tutorial/zh.javascript.info/assets/47357585/08b599f3-4474-4798-b232-563a4ba304a5)

另外分割表达式在常见搜索引擎中并没有比较可靠的检索源，不太清楚你所指的具体来源。

如果有其他问题可以继续补充～

**Comment by huashen84** [comment]
感谢回复。我没表述清楚，不是针对“逗号运算符”的翻译哈，感觉“逗号运算符”分割的是表达式而不是语句。

原文：逗号运算符能让我们处理多个语句，使用 , 将它们分开。每个语句都运行了，但是只有最后的语句的结果会被返回。

我理解的：逗号运算符能让我们处理多个表达式，使用 , 将它们分开。每个表达式都计算了，但是只有最后的表达式的结果会被返回。

![image](https://github.com/javascript-tutorial/zh.javascript.info/assets/4435492/89cd6fdc-b37b-42b1-9100-d83872d1309b)

**Comment by songhn233** [comment]
@huashen84，感谢指出，这里确实有必要区分语句（statement）和表达式（expression）。
