### ISSUE TITLE
4.8节"对象 —— 原始值转换"的"成就"一词

### ISSUE THREAD

**Issue by huanganding** [javascript-tutorial/zh.javascript.info#1159]
> 例如，我们无法使用对象来表示向量或矩阵（或成就或其他）...
这里的”成就“(英文版为achievements)一次是否还有更好的中文翻译？

**Comment by songhn233** [comment]
感谢建议。我理解 achievements 在这里更倾向于解释为成绩记录/完成情况，实际应用为将两个记录直接相加得到合并后的记录。

但其实感觉还是不太好理解，需要更多补充的上下文，实际上向量和矩阵的例子已经足够说明问题了。

因此我倾向于直接把括号中的补充内容不做翻译，有其他想法也欢迎沟通。

**Comment by leviding** [comment]
> 感谢建议。我理解 achievements 在这里更倾向于解释为成绩记录/完成情况，实际应用为将两个记录直接相加得到合并后的记录。
> 
> 但其实感觉还是不太好理解，需要更多补充的上下文，实际上向量和矩阵的例子已经足够说明问题了。
> 
> 因此我倾向于直接把括号中的补充内容不做翻译，有其他想法也欢迎沟通。

赞同
