### ISSUE TITLE
呼叫转移（call forwarding）翻译不当

### ISSUE THREAD

**Issue by dokcn** [javascript-tutorial/zh.javascript.info#1160]
[函数进阶内容 -》装饰器模式和转发，call/apply -》func.apply](https://zh.javascript.info/call-apply-decorators#funcapply)一节「将所有参数连同上下文一起传递给另一个函数被称为“呼叫转移（call forwarding）”。」，其中call forwarding应翻译为调用转发
![IMG_6484](https://github.com/javascript-tutorial/zh.javascript.info/assets/24841978/d4abbbf4-20f1-487f-a63b-ea3802821e60)

**Comment by dokcn** [comment]
![IMG_6485](https://github.com/javascript-tutorial/zh.javascript.info/assets/24841978/6e336e0f-8cd1-4307-a1c3-ffe3c9142554)
总结中的翻译请一并替换

**Comment by songhn233** [comment]
感谢建议，我检索了一下常见搜索引擎发现似乎并没有比较共识的译文，「呼叫转移」是电话相关领域的名词，因此在编程语言上下文中可以采用更恰当的翻译。

我觉得「调用转发」或「调用传递」都比较合适，看看最后确定哪个，后续会把中文仓库相关内容都做一下修改。 

cc @leviding

**Comment by leviding** [comment]
调用传递投一票

**Comment by leviding** [comment]
> 感谢建议，我检索了一下常见搜索引擎发现似乎并没有比较共识的译文，「呼叫转移」是电话相关领域的名词，因此在编程语言上下文中可以采用更恰当的翻译。
> 
> 我觉得「调用转发」或「调用传递」都比较合适，看看最后确定哪个，后续会把中文仓库相关内容都做一下修改。
> 
> cc @leviding

@songhn233 我已经把本 issue 提到的呼叫转移改为了调用传递 https://github.com/javascript-tutorial/zh.javascript.info/commit/ca47903cc6da69d5ed46ea4fe44f5db9002ca683

你有发现其他需要改的位置吗？如果有的话可否提个 PR
