### ISSUE TITLE
“是为了实现简单，可靠且快速地实现解析算法” 语句不通顺

### ISSUE THREAD

**Issue by dokcn** [javascript-tutorial/zh.javascript.info#1163]
[JSON.parse](https://zh.javascript.info/json#jsonparse)最后一段[常规的 JSON 格式严格，并不是因为它的开发者很懒，**而是为了实现简单，可靠且快速地实现解析算法**。]改成[常规的 JSON 格式严格，并不是因为它的开发者很懒，**而是为了简单，可靠且快速地实现解析算法**。]是否更恰当？

**Comment by songhn233** [comment]
Related PR: https://github.com/javascript-tutorial/zh.javascript.info/pull/1164

另外把前文也稍微调整了下，“常规的 JSON 格式” 按照上下文来说称为 “标准 JSON” 更合适（相较 BSON、JSON5）

“开发者” 改为了 “制定者们”，毕竟 JSON 有对应的 RFC 标准，“开发者” 这个说辞感觉不太合适
