### ISSUE TITLE
错字 https://zh.javascript.info/recursion#liang-zhong-si-kao-fang-shi

### ISSUE THREAD

**Issue by dokcn** [javascript-tutorial/zh.javascript.info#1169]
![1](https://github.com/javascript-tutorial/zh.javascript.info/assets/24841978/a8bee036-3224-45d9-b695-48bf98063817)
是**在**而不是**再**

**Comment by leviding** [comment]
Thanks, fixed in https://github.com/javascript-tutorial/zh.javascript.info/commit/fbf418287352086a3010ec44e6cd17d4f25fba49
