### ISSUE TITLE
一数组的人

### ISSUE THREAD

**Issue by dokcn** [javascript-tutorial/zh.javascript.info#1170]
1. https://zh.javascript.info/recursion#di-gui-jie-gou **一数组的人**翻译不当，原文**Either an array of people.** 个人理解翻译为**人员数组**或许更恰当
![2](https://github.com/javascript-tutorial/zh.javascript.info/assets/24841978/63243175-18e6-4baa-8fda-e3adf2644689)

1. https://zh.javascript.info/recursion#di-gui-bian-li **一个部门可能有一 数组 的员工** 建议翻译为**一个部门可能有一个员工数组**
![2 1](https://github.com/javascript-tutorial/zh.javascript.info/assets/24841978/22a25f9c-65a1-46a8-8e55-545f486f405f)

**Comment by leviding** [comment]
Thanks, fixed in https://github.com/javascript-tutorial/zh.javascript.info/commit/fbf418287352086a3010ec44e6cd17d4f25fba49
