### ISSUE TITLE
有序结构必须可以快速地从两端添加/移除元素，但是不需要访问的元素。https://zh.javascript.info/recursion#di-gui-jie-gou

### ISSUE THREAD

**Issue by dokcn** [javascript-tutorial/zh.javascript.info#1171]
![3](https://github.com/javascript-tutorial/zh.javascript.info/assets/24841978/2d0c221d-6ba9-4201-ae73-adc4f3dcf0cc)
后半句的原文是： but access to its middle is not needed.
所以**但是不需要访问的元素**应翻译为**但是不需要访问位于中间的元素**

**Comment by leviding** [comment]
Thanks, fixed in https://github.com/javascript-tutorial/zh.javascript.info/commit/fbf418287352086a3010ec44e6cd17d4f25fba49
