### ISSUE TITLE
直到结束 let（“死区”）翻译不当 https://zh.javascript.info/task/let-scope

### ISSUE THREAD

**Issue by dokcn** [javascript-tutorial/zh.javascript.info#1172]
建议翻译为：引擎从函数开始就知道局部变量 x， 但是变量 x 一直处于“未初始化”（无法使用）的状态，直到遇到let，此时“死区”结束
![5](https://github.com/javascript-tutorial/zh.javascript.info/assets/24841978/4308320b-19ca-4ed8-9c4b-9a052b6668bd)

**Comment by dokcn** [comment]
另外本题中提到的let换成const应该是同样适用的，是否需要添加说明？

**Comment by leviding** [comment]
> 另外本题中提到的let换成const应该是同样适用的，是否需要添加说明？

题目只涉及 let 就先只管 let 吧

**Comment by leviding** [comment]
Thanks, fixed in https://github.com/javascript-tutorial/zh.javascript.info/commit/fbf418287352086a3010ec44e6cd17d4f25fba49
