### ISSUE TITLE
翻译句意有误

### ISSUE THREAD

**Issue by CharlezXue** [javascript-tutorial/zh.javascript.info#1176]
在 [Symbol ](https://javascript.info/symbol#symbol-keyfor)一节，英文是：
> ... If the symbol is not global, it won’t be able to find it and returns `undefined`.
> **That said**, all symbols have the description property. 

而[中文](https://zh.javascript.info/symbol#symbolkeyfor)是：
> ...如果 symbol 不是全局的，它将无法找到它并返回 `undefined`。
> **也就是说**，所有 symbol 都具有 description 属性。

原文表达转折（但是、话虽如此）。并非中文表示的因果关系。

**Comment by leviding** [comment]
感谢指出，已订正 https://github.com/javascript-tutorial/zh.javascript.info/pull/1179
