### ISSUE TITLE
关于中英对照的版本

### ISSUE THREAD

**Issue by gledfish** [javascript-tutorial/zh.javascript.info#1178]
考虑弄一个**中英文对照**的版本吗？简单的部分直接阅读中文，不懂或者模糊的地方进行中英对照，可能会更适合理解。这样也有助于提高英文水平。（不过这样可能显得排版很臃肿）

**Comment by xuesongde** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by leviding** [comment]
谢谢建议，目前不考虑这样做。
