### ISSUE TITLE
Garbage collection: ' They are guaranteed to be stored in memory.' was translated by '它们一定是存储在内存中的'

### ISSUE THREAD

**Issue by zaggerj** [javascript-tutorial/zh.javascript.info#1181]
'它们确保被存储在内存中'

**Comment by zaggerj** [comment]
(there are some other, internal ones as well) was translated by（还有一些内部的）
it should be '还有一些其他的，内部实现','internal ones' should be '内部的' '东西'

**Comment by zaggerj** [comment]
'Any other value is considered reachable if it’s reachable from a root by a reference or by a chain of references.' was translated by（'如果一个值可以通过引用链从根访问任何其他值，则认为该值是可达的'
it should be '如果一个值可以从根通过引用或者引用链进行访问，则认为该值是可达的'

**Comment by zaggerj** [comment]
Static properties and methods
'We can also assign a method to the class as a whole' should be '我们还可以为整个类分配一个方法' not be  '我们可以把一个方法作为一个整体赋值给类'

**Comment by leviding** [comment]
谢谢您提出的建议，均已更新。欢迎继续提出宝贵建议

https://github.com/javascript-tutorial/zh.javascript.info/commit/6baa9ebdcfb030323d431a69fec3c2ff7edbfcf3
https://github.com/javascript-tutorial/zh.javascript.info/commit/4643531e1e8fc3f25e35c4534f41ae71421103e8
