### ISSUE TITLE
"Class基本语法"一节中，对类字段特性的描述

### ISSUE THREAD

**Issue by xiaoyan13** [javascript-tutorial/zh.javascript.info#1185]
在[Class 字段](https://zh.javascript.info/class#class-zi-duan)一小节中，描述了一个特性：
> ”类字段重要的不同之处在于，它们会在每个独立对象中被设好，而不是设在 User.prototype“。

无论使用类字段、在 `constructor` 中使用 `this` 赋值、还是直接使用构造函数 +`new`，属性设置都是在对象中的，而非在构造函数的prototype（或对象的__proto__）。该句话存在误导性。

**Comment by xiaoyan13** [comment]
作者想表达应该是：相对于类中的方法（它们会挂到函数的prototype上），使用带”=“的类字段，会挂到每个实例上而非对象原型上。

**Comment by leviding** [comment]
已更新为：类字段的重要区别在于，它们会被挂在实例对象上，而非 `User.prototype` 上 https://github.com/javascript-tutorial/zh.javascript.info/commit/9f949bfc2dbbf49cbd0aadfa4159b51b41ecaf1e

你看怎么样，此 issue 暂时关闭，如有后续提议，欢迎 reopen 或新建一个 issue，或者直接提 pull request
