### ISSUE TITLE
Polyfill 和转译器章节有一个链接 404

### ISSUE THREAD

**Issue by leviding** [javascript-tutorial/zh.javascript.info#1198]
https://zh.javascript.info/polyfills

![image](https://github.com/javascript-tutorial/zh.javascript.info/assets/26959437/695c8106-5fce-4fc4-b272-478c4a3b0064)

**Comment by inspirewind** [comment]
现在可用的链接应该是https://compat-table.github.io/compat-table/es6/

**Comment by leviding** [comment]
谢谢，已更新
