### ISSUE TITLE
目录层次没有清晰展示

### ISSUE THREAD

**Issue by meowlgmee** [javascript-tutorial/zh.javascript.info#1226]
点击某个主题进入阅读后, 建议左侧边栏显示完整的目录信息比较好. 目前只能看见当前小主题的琐碎目录, 还是把整个体系的目录都显示出来比较好, 便于导航.

**Comment by xuesongde** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by leviding** [comment]
谢谢建议，目前这是网站的风格，暂不会改动
