### ISSUE TITLE
Bug-report?

### ISSUE THREAD

**Issue by iliakan** [javascript-tutorial/zh.javascript.info#276]
Hello,I'm a chinese JS beginner learning from you.

I‘m not good at english, so I just go straight.

In this website:

https://zh.javascript.info/type-conversions 

this part:                         

――――――――――――――――――――――――――begin――――――――――――――――――――――――――――――――――――――――――――――――――――――

number 类型转换规则：

值	变成…
undefined	NaN
null	0
true 和 false	1 and 0
string	字符串开始和末尾的空白会被移除，剩下的如果是空字符串，结果为 0，否则 ―― 从字符串中读出数字。错误返回 NaN
―――――――――――――――――――――――――end―――――――――――――――――――――――――――――――――――――――――――――――――――――――

The description of ”string“ is grammatically wrong sentence.

The meaning of this passage("字符串开始和末尾的空白会被移除，剩下的如果是空字符串，结果为 0，否则 ―― 从字符串中读出数字。错误返回 NaN") is “The whitespace at the beginning and end of the string will be removed, and if the rest is an empty string, the result is 0, otherwise -- the number is read from the string.Error returns NaN”.

Accuracy, it should be  “The whitespace at the beginning and end of the string will be removed, and if the rest is an empty string, the result is 0, ‘WHEN THE REST ISN'T EMPTY,IF IT IS NUMBER , READING IT FROM THE STRING,OTHERWISE RETURNS NaN'” .

    e.g."4px" - 2 returns NaN,but it easy to get a wrong answer -- 2，because “ the number is read from the string”.

Because my level is very poor,I can only guarantee what is wrong, but I can't guarantee that my description is correct.

Yours faithfully,
zongjiezhe

zhuqiang@mododata.com

**Comment by zongjiezhe** [comment]
thks

**Comment by leviding** [comment]
@zongjiezhe 你好啊，你发邮件指的问题，是什么意思呢，现在问题是否还存在，可以在这留言，我把问题解决掉，然后关闭 issue 哈
