### ISSUE TITLE
表述问题

### ISSUE THREAD

**Issue by illionhh** [javascript-tutorial/zh.javascript.info#282]
其他数字函数这一段中有一个小问题
Math.pow(n,power)
返回经过 n 进制转换的 power 值,假如参数为2,10,最后的计算结果为1024,实际上Math.pow()函数为次方计算函数吧.也就是n**power

**Comment by leviding** [comment]
欢迎 PR

**Comment by leviding** [comment]
@illionhh 能给出具体章节链接吗？

**Comment by leviding** [comment]
原文链接详见：https://github.com/javascript-tutorial/zh.javascript.info/blob/5c118be9be46048d7c253308a72c7a2499149ee3/1-js/05-data-types/02-number/article.md

**Comment by leviding** [comment]
教程内容如下：

---

## 其他数学函数

JavaScript 有一个内置的 [Math](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Math) 对象,包含一个数学函数和常量的小型库的对象。

几个例子：

`Math.random()`
: 返回从 0 到 1 的随机数（不包括 1）

    ```js run
    alert( Math.random() ); // 0.1234567894322
    alert( Math.random() ); // 0.5435252343232
    alert( Math.random() ); // ... (any random numbers)
    ```

`Math.max(a, b, c...)` / `Math.min(a, b, c...)`
: 从任意数量的参数中返回最大/最小值。

    ```js run
    alert( Math.max(3, 5, -10, 0, 1) ); // 5
    alert( Math.min(1, 2) ); // 1
    ```

`Math.pow(n, power)`
: 返回 n 的 power 次幂，即 n<sup>power</sup>

    ```js run
    alert( Math.pow(2, 10) ); // 2 的 10 次幂 = 1024
    ```

这里有 `Math` 对象中的更多函数和常量，包括三角函数，你可以在这里找到它 [docs for the Math](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Math)。

---

我认为没有什么问题啊，是次方计算。

**Comment by leviding** [comment]
issue 先关闭了，有问题再开 issue 哈，或者在本 issue 下艾特我，因为暂时没有看出哪里有表述问题。
