### ISSUE TITLE
排序对象的解决方式是有问题的

### ISSUE THREAD

**Issue by callren** [javascript-tutorial/zh.javascript.info#292]
https://zh.javascript.info/array-methods#jiang-borderleftwidth-zhuan-huan-cheng-borderleftwidth

function sortByName(arr) {
  arr.sort((a, b) => a.name > b.name);
}

let john = { name: "John", age: 25 };
let pete = { name: "Pete", age: 30 };
let mary = { name: "Mary", age: 28 };

let arr = [ john, pete, mary ];

sortByName(arr);

// 现在排序是：[john, mary, pete]
alert(arr[1].name); // Mary

如果你测试了就会发现这个打印出来的是pete

正确的是需要修改arr.sort((a, b) => a.age - b.age);

**Comment by leviding** [comment]
欢迎到原英文 repo 提 PR，以修正错误，原 repo 修正后，欢迎 PR 到本 repo。

**Comment by leviding** [comment]
本章节内容需要同步更新到英文最新版：https://en.javascript.info/array-methods#jiang-borderleftwidth-zhuan-huan-cheng-borderleftwidth
