### ISSUE TITLE
Objects（对象）：基础知识 这一章的排版有点问题.

### ISSUE THREAD

**Issue by h-j-13** [javascript-tutorial/zh.javascript.info#301]
https://zh.javascript.info/object 具体在  `属性值简写` 这个小节里,截图如下

![QQ截图20190321195138.png](https://upload-images.jianshu.io/upload_images/5617720-45cbc867f6855f88.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by h-j-13** [comment]
[字符串](https://zh.javascript.info/string) 这一章也有点格式问题
![image.png](https://upload-images.jianshu.io/upload_images/5617720-78ef7df1f8988698.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by h-j-13** [comment]
[日期与时间](https://zh.javascript.info/date) 同上
![image](https://user-images.githubusercontent.com/20575663/55270522-85a45b80-52da-11e9-98da-4b6c9d3becfa.png)

**Comment by leviding** [comment]
前两个已修复，第三个正在排查

**Comment by leviding** [comment]
问题均已解决，本 issue 关闭。
