### ISSUE TITLE
【值的比较】这一页排版有问题

### ISSUE THREAD

**Issue by ChungZH** [javascript-tutorial/zh.javascript.info#304]
[值的比较](https://zh.javascript.info/comparison) 这里出现了一些很奇怪的问题，如下：

![](https://i.loli.net/2019/03/23/5c95ceacc862c.png)
![](https://i.loli.net/2019/03/23/5c95ceacca516.png)

~~我看 Markdown 格式看不出问题 逃~~

**Comment by leviding** [comment]
修复了，感谢。
