### ISSUE TITLE
Conflict Translation: attribute & property

### ISSUE THREAD

**Issue by MartinsYong** [javascript-tutorial/zh.javascript.info#321]
[目标文档](https://github.com/xitu/javascript-tutorial-zh/blob/zh-hans/2-ui/1-document/06-dom-attributes-and-properties/article.md)

[Target Doc](https://github.com/xitu/javascript-tutorial-zh/blob/zh-hans/2-ui/1-document/06-dom-attributes-and-properties/article.md)

“attribute”和“property”直接翻译成“特性”和“属性”难免让人误解。本来在实际概念里面就容易混淆，作者特意拿来作对比，所以我觉得**应该直接当作特有名词，不译即可**。

其实，通过英文的字面意思，对JavaScript有一定了解的读者可作贯通理解：
“attribute” --> Attribute 节点 --> 可通过元素节点实例调用`hasAttribute`、`setAttribute`等方法进行操作；
“property” --> 广义的js对象属性 --> 可通过`Object​.get​OwnProperty​Descriptor`、`Object​.get​OwnProperty​Names`、`Object​.prototype​.has​OwnProperty`等方法进行操作。

**Comment by leviding** [comment]
已经 merge 了，非常感谢。
