### ISSUE TITLE
Recent changes

### ISSUE THREAD

**Issue by iliakan** [javascript-tutorial/zh.javascript.info#386]
Hi,

I renamed some stuff in `1-js/5-network` and `1-js/11-async`.

As a side effect, when you pull from upstream (from English version), git doesn't always recognize the renaming, and creates both English and Chinese versions, e.g.

- `1-js/11-async/05-async-await` - old name (Chinese)
- `1-js/11-async/08-async-await` - new name (English)

Please, remove `1-js/11-async/08-async-await`. Instead, rename `1-js/11-async/05-async-await` to `1-js/11-async/08-async-await`, and adapt latest English changes to it.

Also, the Chinese version doesn't have chapter `1-js/11-async/06-promisify`, no idea why.

P.S. Similar thing may happen with `url` chapter in `networking` when you next time pull upstream.

**Comment by MartinsYong** [comment]
I will check out the article `1-js/11-async/08-async-await`.

**Comment by MartinsYong** [comment]
Solved~

**Comment by MartinsYong** [comment]
Solved~

**Comment by leviding** [comment]
@MartinsYong 那就 close 啦
