### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by lj0812** [javascript-tutorial/zh.javascript.info#393]
第28章第7节 插值方法->在相邻的 HTML 标签中插入/文本/元素 的内容有4处同样的错误

![image](https://user-images.githubusercontent.com/29274526/60947581-7abe8580-a323-11e9-9bca-0d6000aa5ba2.png)

**Comment by lycheeEng** [comment]
已经添加 PR #394 修复此错误。

另外这篇文章英文版内容有修改：增加了一节内容。

**Comment by lycheeEng** [comment]
PR #394 已 merge，新增的内容已经提交 PR #396 

感谢提交 Issue！
