### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by tianfeng65** [javascript-tutorial/zh.javascript.info#395]
promise章节这一句话写错了
![image](https://user-images.githubusercontent.com/39827055/61041714-6357c900-a405-11e9-9e05-6c7657f52122.png)

**Comment by lycheeEng** [comment]
感谢提交 Issue！

具体问题在这里：[Promises 链#总结](http://zh.javascript.info/promise-chaining#zong-jie)

英文原文是这样的：`If it throws an error, then the new promise becomes rejected, and the closest rejection handler (second argument of `.then` or `.catch`) is called with it.`

这里的翻译确实有点问题，你图片中这样换一下位置即 `.then 的第二个参数或者 .catch` 意思就对了！

但这里有个小问题就是英文版的这一章作者已经更新，这部分内容被删除了，中文版的这部分内容也将会会同步更新。所以要不这个 Issue 就先放这里？等中文翻译修改更新后再做处理吧。

再次感谢！

**Comment by leviding** [comment]
@lycheeEng 本 issue 问题已经解决了？

**Comment by lycheeEng** [comment]
@leviding 解决了，刚刚 merge 的 PR 修复了这个问题。
