### ISSUE TITLE
中文文档中未删除英文原文

### ISSUE THREAD

**Issue by lj0812** [javascript-tutorial/zh.javascript.info#398]
第28章11节坐标->使用位置fixed

![image](https://user-images.githubusercontent.com/29274526/61101169-68ffee00-a49b-11e9-8bb3-74f7087b80a4.png)

**Comment by MartinsYong** [comment]
如果可以的话，可以PR一下~

**Comment by lj0812** [comment]
好的，我晚些时候尝试一下
