### ISSUE TITLE
本地运行服务端预览中文版文档时出错

### ISSUE THREAD

**Issue by yingziwu** [javascript-tutorial/zh.javascript.info#402]
按照[教程](https://github.com/javascript-tutorial/server)完成安装后，可正常预览英文版，但预览中文版文档时出错。简单搜索了一下，发现了一个可能相关的 [Issue](https://github.com/javascript-tutorial/engine/pull/22)。

错误日志：[edit_zh_log.tar.gz](https://github.com/javascript-tutorial/zh.javascript.info/files/3395844/edit_zh_log.tar.gz)

**Comment by MartinsYong** [comment]
谢谢反馈~主要原因是某些文章出现重复了，正在修复中。

**Comment by MartinsYong** [comment]
您现在可以更新一下，并再次尝试~

**Comment by leviding** [comment]
@yingziwu 您可以更新下看看是否还有问题，如果没有的话，麻烦关一下 issue 哈~
