### ISSUE TITLE
欢迎加入本教程读者交流群 🎉

### ISSUE THREAD

**Issue by leviding** [javascript-tutorial/zh.javascript.info#413]
| 微信扫码关注官方公众号，订阅更多精彩内容 |
|-|
|  <img src="https://i.loli.net/2020/07/07/CbUGTm1sWD5V4HO.png" width="500px;" /> |

**加入读者交流群：**

- **微信群**：加微信 **`imleviding`** 或 [扫二维码](https://user-images.githubusercontent.com/26959437/64596211-0fa63380-d3e6-11e9-983d-bd788ffe2370.jpg)，验证信息填写 **`JS 教程`**。
- **QQ 群**：打开 QQ 搜索群号 **`866757202`** 或 [扫二维码](https://user-images.githubusercontent.com/26959437/64609229-12f9e900-d3ff-11e9-96e8-147335f5e264.jpg)，验证信息填写 **`JS 教程`**。
- **Telegram**：https://t.me/TheModernJavaScriptTutorial
- **Gitter**：[点击加入 Gitter Room](https://gitter.im/zh-javascript-info/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by itboos** [comment]
你好，想问现在这个教程翻译完了没，想参与翻译。我看那个翻译进度的issue， 为什么好多没有勾选的文章点进去也是中文版的呀，是没有同步还是怎么回事呢

**Comment by leviding** [comment]
@itboos 教程正在全面检查更新，检查并更新完毕的会被勾选。没检查更新完毕的，以及没翻译完成的，都没有勾选，欢迎参与贡献。

**Comment by cyz980908** [comment]
@leviding 您好~为什么列表里有的文章 404 了啊？

**Comment by leviding** [comment]
@cyz980908 404 是英文版新增加的章节，没有同步到本项目，哪个 404 了，麻烦指出来，我更新进来。

**Comment by xkoko123** [comment]
讨厌死了...zh.javascript.info上写的请 帮助我们 将其翻译为 简体中文 版本。。我想都没想就点开直接翻译，翻译完才发现已经被翻译过了。

**Comment by leviding** [comment]
> 讨厌死了...zh.javascript.info上写的请 帮助我们 将其翻译为 简体中文 版本。。我想都没想就点开直接翻译，翻译完才发现已经被翻译过了。

🤣 以 GitHub 为准，因为有很多东西还在 Review 中。

**Comment by github15238484509** [comment]
> 

你太惨了

**Comment by wastu01** [comment]
不知有無繁體中文版

**Comment by songhn233** [comment]
> 不知有無繁體中文版

Hello，有一个 [仓库](https://github.com/javascript-tutorial/zh-hant.javascript.info)，但是目前状态未知
