### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by zhouzhouyou** [javascript-tutorial/zh.javascript.info#441]
https://zh.javascript.info/string#huo-qu-zi-zi-fu-chuan
str.substring(start [, end])部分
原文为：
> Negative arguments are (unlike slice) not supported, they are treated as 0.

译文为：
> 否定参数（不像 slice）不支持，它们被视为 0。

个人认为`否定参数`为翻译错误，应该为负值 :cry:

**Comment by lycheeEng** [comment]
感谢提交 issue。
翻译成 `负值` 是对的。
这个文件对比英文版还有其他修改的地方。晚点我再一并修改。
再次感谢~

**Comment by lycheeEng** [comment]
已经在 PR #443 中修复此问题。请参见 article.md 文件的第 `429行`。

**Comment by lycheeEng** [comment]
已修复。再次感谢！
