### ISSUE TITLE
Bugs for the website of zh.javascript.info.

### ISSUE THREAD

**Issue by leviding** [javascript-tutorial/zh.javascript.info#540]
As shown in the pictures below:

![image](https://user-images.githubusercontent.com/26959437/69702314-e1eda280-1129-11ea-8c87-9ea07346f79f.png)

![image](https://user-images.githubusercontent.com/26959437/69702281-cd110f00-1129-11ea-81ae-885facfabb4c.png)

**Comment by leviding** [comment]
@iliakan

**Comment by iliakan** [comment]
(continued in wechat)
