### ISSUE TITLE
this 复杂调用 示例代码好像有bug

### ISSUE THREAD

**Issue by PikaBin** [javascript-tutorial/zh.javascript.info#554]
关于 对象方法与this 这一节，当我看到 “复杂的方法调用可能会导致this丢失”，然后试着直接将下面一个通过三元运算符去调用函数的 代码直接粘贴到浏览器运行的时候，并没有发现预期中的error，反而能够正常运行，请问这是不是出现了bug？我用的是Chrome浏览器

**Comment by bemself** [comment]
@PikaBin 为方便别人快速 get 到你的问题，最好直接把原文出处、所运行的代码一并贴出来，以及你观察到的实际结果，和你预期的结果。我先帮你挪一点过来：

[对象方法与 "this"](https://github.com/javascript-tutorial/zh.javascript.info/blob/master/1-js/04-object-basics/04-object-methods/article.md)

代码：
```
let user = {
  name: "John",
  hi() { alert(this.name); },
  bye() { alert("Bye"); }
};

user.hi(); // John (the simple call works)

// 现在我们要判断 name 属性，来决定调用 user.hi 或是 user.bye。
(user.name == "John" ? user.hi : user.bye)(); // Error!
```

**Comment by PikaBin** [comment]
对的，就是这处代码，我直接复制到浏览器里运行时，并没有出现 在原文代码块环境运行的错误，如图一，
具体的链接地址如下：对象方法与this
&nbsp;图二是我自己的本地HTML文件里面引入js文件然后在浏览器里运行的结果（这两个文件均添加在附件里了），我也很好奇为什么结果不一致？所以怀疑是不是有bug，或者环境不一致？
第一次提issue，不知道具体规范，给你带来麻烦很抱歉


图一

图二









------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"bemself"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月9日(星期一) 晚上7:40
收件人:&nbsp;"javascript-tutorial/zh.javascript.info"<zh.javascript.info@noreply.github.com&gt;;
抄送:&nbsp;"华侨大学  李嘉宾"<1747320015@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [javascript-tutorial/zh.javascript.info] this 复杂调用 示例代码好像有bug (#554)




@PikaBin 为方便别人快速 get 到你的问题，最好直接把原文出处、所运行的代码一并贴出来，以及你观察到的实际结果，和你预期的结果。我先帮你挪一点过来：
 
对象方法与 "this"
 
代码：
 let user = {   name: "John",   hi() { alert(this.name); },   bye() { alert("Bye"); } }; user.hi(); // John (the simple call works) // 现在我们要判断 name 属性，来决定调用 user.hi 或是 user.bye。 (user.name == "John" ? user.hi : user.bye)(); // Error!

**Comment by bemself** [comment]
@PikaBin 看不到你的截图，邮件中也没有看到附件，方便再贴一下吗？

**Comment by bemself** [comment]
@PikaBin 我试着跑了一下代码，可能有些明白你的困惑，试着解一下，抛砖引玉，因为我 js 不太熟。

因为看不到你的截图，所以我只是猜测，如果不对请指正：
- 我感觉，你的困惑在于 Error 的表现形式，可能认为 Error 一定是那种一串 stacktrace 类似的，
   - 但在浏览器的运行结果看似正常（没有报错），但实际上并没有返回期望的结果对吗？   
   - 这其实也是 Error 的一种形式，因为浏览器足够友好，将错误已经 catch 并做了友好处理。
   - 如果你将这段脚本放到浏览器控制台中运行，会看到 undefined, 说明内部已经是出错了。

贴一下我观察到的结果：

- 在 浏览器 中运行时， alert 窗口显示是空值，控制台显示是 undefined 
![image](https://user-images.githubusercontent.com/45781328/70529523-b8059880-1b8b-11ea-8352-4328ea06e44d.png)
![image](https://user-images.githubusercontent.com/45781328/70529571-c94ea500-1b8b-11ea-8fca-5e7850830195.png)

- 在 IDE 中运行时，因为没有做友好处理，所以可以看到实际的报错：
![image](https://user-images.githubusercontent.com/45781328/70532266-a626f400-1b91-11ea-8993-515d8e1566d4.png)

**Comment by PikaBin** [comment]
对，我也遇到了这种情况，你这样一说确实明白了，但是我后来
分别建立一个HTML文件和js文件，然后将js文件引入到html文件，然后用浏览器打开，就会出现alert 提示框并且显示bye，这是为什么呢？

**Comment by PikaBin** [comment]
具体现象就是如图:

![js-this](https://user-images.githubusercontent.com/39492945/70533855-e176f200-1b94-11ea-80d8-2cb956b79865.png)

**Comment by bemself** [comment]
@PikaBin 最好把你的源文件代码一并放上来，方便别人重现你的问题

**Comment by PikaBin** [comment]
嗯好，
注意 引入js文件的路径要修改
HTML文件源代码：
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>JavaScript</title>
<script type="text/javascript" src="../js/test.js"></script>
</head>
<body>

<h1>我的 JavaScript 程序</h1>
<p id="demo">这是一个段落</p>
<p id="test"></p>

<button type="button" onclick="displayDate()">显示日期</button>
<button type="button" onclick="displayTitle(a) ">显示标题</button>

</body>
</html>

js文件源代码：
let user = {
    name: "John",
    hi() { alert(this.name); },
    bye() { alert("Bye"); }
  };
(user.name=='john'?user.hi:user.bye)()

**Comment by bemself** [comment]
@PikaBin 看到了，提示一下，最后的三元运算，user.name=="john" 实际结果是 false，所以走了 bye(), 而 bye()里面并没有用到 this，所以你懂得。至于为什么判断结果是 false，您在仔细看下代码~

**Comment by PikaBin** [comment]
不好意思，太沙雕了，老哥，多谢了
