### ISSUE TITLE
while-for页面翻译

### ISSUE THREAD

**Issue by yyxygit** [javascript-tutorial/zh.javascript.info#567]
[while-for页面](https://zh.javascript.info/while-for)

> 禁止 break/continue 在‘?’的右边

模块最后一行译文：

> 这只是不使用 ? 而不是 if 的另一个原因。

[原文](https://javascript.info/while-for)

> This is just another reason not to use the question mark operator ? instead of if.

这是不（建议）使用问号？操作符替代if语句的原因之一。

这样？

**Comment by leviding** [comment]
这种优化可以，你可以提一个 PR

**Comment by leviding** [comment]
solved.
