### ISSUE TITLE
js部分的“对象方法与this”章节中有如下题目的答案有误！

### ISSUE THREAD

**Issue by greenplumm** [javascript-tutorial/zh.javascript.info#594]
在对象字面量中使用 "this"
重要程度: 5
这里makeUser函数返回了一个对象。访问ref的结果是什么？为什么？
function makeUser(){
    return{   
      name:"John",   
      ref:this};
 };
let user =makeUser();
alert( user.ref.name );// What's the result? 

书中给出的答案有误： // Error: Cannot read property 'name' of undefined
题中的this应该是window对象在非严格模式下，故window.name为空字符串吧

**Comment by leviding** [comment]
本教程是现代 JavaScript 教程，默认是在严格模式下的，所以是 undefined。

感谢提问。
