### ISSUE TITLE
Solution.js display unormal in zh website

### ISSUE THREAD

**Issue by leviding** [javascript-tutorial/zh.javascript.info#638]
Update: When there are no words in solution.md, but there some words in solution.js. On en website, solution.js can show well, but on zh website they are not shown.

Here are some links to this situation (Not all links of this situation):

- https://zh.javascript.info/object#shu-zhi-shu-xing-du-cheng-yi-2
- https://zh.javascript.info/array-methods#cong-shu-zu-chuang-jian-jian-zhi-dui-xiang
- https://zh.javascript.info/map-set#guo-lv-zi-mi-anagrams
- https://zh.javascript.info/string#ti-qu-huo-bi
- https://zh.javascript.info/array-methods#jiang-borderleftwidth-zhuan-huan-cheng-borderleftwidth
- https://zh.javascript.info/array-methods#cong-shu-zu-chuang-jian-jian-zhi-dui-xiang
- https://zh.javascript.info/map-set#guo-lv-shu-zu-zhong-de-wei-yi-yuan-su
- https://zh.javascript.info/keys-values-entries#ji-suan-shu-xing-shu-liang
- https://zh.javascript.info/destructuring-assignment#zui-gao-xin-zi
- https://zh.javascript.info/date#ou-zhou-de-xing-qi-biao-shi-fang-fa
- https://zh.javascript.info/class#zhong-xie-wei-class
- https://zh.javascript.info/class-inheritance#ji-cheng-clock

----

For example, solution of this task have a solution.js:

<img width="1006" alt="Screen Shot 2020-03-05 at 1 06 38 PM" src="https://user-images.githubusercontent.com/26959437/75949753-27b4c680-5ee2-11ea-8bd6-1fc00b3949cf.png">

And it shows normally on en website as shown in the picture below:

<img width="739" alt="Screen Shot 2020-03-05 at 1 08 04 PM" src="https://user-images.githubusercontent.com/26959437/75949822-5b8fec00-5ee2-11ea-9924-20cb2462a449.png">

On zh website: there is also a solution.js:

<img width="1017" alt="Screen Shot 2020-03-05 at 1 09 04 PM" src="https://user-images.githubusercontent.com/26959437/75949866-7f533200-5ee2-11ea-8ce7-bb85f4f3f45f.png">

But it does not show on zh website:

<img width="758" alt="Screen Shot 2020-03-05 at 1 09 46 PM" src="https://user-images.githubusercontent.com/26959437/75949895-985be300-5ee2-11ea-9e2b-2c62c586d1a6.png">

All solution.js are not shown on zh website.

It's so kind of you @iliakan if you can solve this problem.

Best,
Levi Ding

**Comment by leviding** [comment]
Another problem about css, both in zh and en website: text after the serial number is displayed on a new line as shown in the picture below:

<img width="896" alt="Screen Shot 2020-03-05 at 1 13 45 PM" src="https://user-images.githubusercontent.com/26959437/75950273-ac541480-5ee3-11ea-93b3-4e6a4ed300d6.png">

Is this what we want it to show, or it is a mistake?

Thanks again!

**Comment by leviding** [comment]
I have updated the explanation of the problem.

**Comment by leviding** [comment]
Auto-updates do not work automatically, is there anything wrong? @iliakan 
For example this character: https://zh.javascript.info/try-catch

**Comment by iliakan** [comment]
@leviding All auto-updates are down due to a problem in puppeteer module, exploring and fixing this ASAP.

**Comment by leviding** [comment]
Got it. Thanks!

**Comment by iliakan** [comment]
Fixed.

**Comment by iliakan** [comment]
Lists are on newlines due to styling nuances, we decided to let it be.

**Comment by iliakan** [comment]
Solutions → exploring.

**Comment by iliakan** [comment]
@leviding are solutions ok now?

**Comment by leviding** [comment]
@iliakan Yes, that's awesome!
