### ISSUE TITLE
翻译进度 issues 列表中的链接失效

### ISSUE THREAD

**Issue by Isildur46** [javascript-tutorial/zh.javascript.info#742]
截止至北京时间 2020-05-12 13:59 
中文教程翻译进度 issues 中
Chinese Translation Progress #324
https://github.com/javascript-tutorial/zh.javascript.info/issues/324
教程列表中有若干链接报404错误，汇总如下

- [x] https://github.com/javascript-tutorial/zh.javascript.info/blob/master/1-js/02-first-steps/07-type-conversions
- [x] https://github.com/javascript-tutorial/zh.javascript.info/blob/master/1-js/02-first-steps/08-operators
- [x] https://github.com/javascript-tutorial/zh.javascript.info/blob/master/1-js/02-first-steps/09-comparison
- [x] https://github.com/javascript-tutorial/zh.javascript.info/blob/master/1-js/02-first-steps/12-nullish-coalescing-operator
- [x] https://github.com/javascript-tutorial/zh.javascript.info/blob/master/1-js/02-first-steps/13-while-for
- [x] https://github.com/javascript-tutorial/zh.javascript.info/blob/master/1-js/02-first-steps/14-switch
- [x] https://github.com/javascript-tutorial/zh.javascript.info/blob/master/1-js/02-first-steps/15-function-basics
- [x] https://github.com/javascript-tutorial/zh.javascript.info/blob/master/1-js/02-first-steps/16-function-expressions
- [x] https://github.com/javascript-tutorial/zh.javascript.info/blob/master/1-js/02-first-steps/17-arrow-functions-basics
- [x] https://github.com/javascript-tutorial/zh.javascript.info/blob/master/1-js/02-first-steps/18-javascript-specials
- [x] https://github.com/javascript-tutorial/zh.javascript.info/blob/master/1-js/04-object-basics/02-object-copy
- [x] https://github.com/javascript-tutorial/zh.javascript.info/blob/master/1-js/04-object-basics/03-garbage-collection
- [x] https://github.com/javascript-tutorial/zh.javascript.info/blob/master/1-js/04-object-basics/07-optional-chaining
- [x] https://github.com/javascript-tutorial/zh.javascript.info/blob/master/1-js/04-object-basics/08-symbol
- [x] https://github.com/javascript-tutorial/zh.javascript.info/blob/master/1-js/04-object-basics/09-object-toprimitive
- [x] https://github.com/javascript-tutorial/zh.javascript.info/blob/master/1-js/99-js-misc/04-reference-type

**Comment by leviding** [comment]
这些链接失效是因为文件夹结构和命名的改变，对内容没有影响，对于读者也没有影响。现已安排在教程维护任务队列，在此 issue 下对进度进行同步。

**Comment by leviding** [comment]
正在解决中……

**Comment by leviding** [comment]
均已修复，感谢 👍
