### ISSUE TITLE
image translation

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/zh.javascript.info#747]
Hi, I'm a maintainer of the Korean version.

I've tried to translate image using the guide on the server README but it's not working somewhat.

I've looked into the Chinese version and found the images are translated. But there is no images.yml file.

How did you do?

**Comment by leviding** [comment]
We just change the field in the SVG file of each image. But I think to follow the guide on the server README is better, and I also tried that way, the same as you, It's not working somewhat. If you have the solution of this problem, please tell me! Thanks!

**Comment by Violet-Bora-Lee** [comment]
Thanks for your comment!
I'll make a new issue on the English repo.
