### ISSUE TITLE
网站有时候访问很快，有时候访问不了，什么原因？

### ISSUE THREAD

**Issue by glzcc** [javascript-tutorial/zh.javascript.info#750]
https://zh.javascript.info/
网站有时候访问很快，有时候访问不了，什么原因？

**Comment by leviding** [comment]
使用的是国外的服务器，需要你保证自己的网络稳定性。

**Comment by gradlexyz** [comment]
可以在国内设置镜像
我有服务器

**Comment by leviding** [comment]
> 可以在国内设置镜像
> 我有服务器

谢谢。其实目前在国内，只要是正常的网络状态，访问教程网站是没有任何问题的。我们再观察观察，如果确实访问体验上有问题，会购买服务器做镜像，因为访问量也挺大的。
