### ISSUE TITLE
6.9 装饰者模式和转发，call/apply 中，防抖装饰器小节有误

### ISSUE THREAD

**Issue by nslyc** [javascript-tutorial/zh.javascript.info#754]
这一部分中，[英文版](https://javascript.info/call-apply-decorators#debounce-decorator) 和 [中文版](https://zh.javascript.info/call-apply-decorators#qu-dou-zhuang-shi-zhe) 对于 **防抖** 的理解和描述完全不一致，建议尽快更正，以免读者对此产生疑惑。

**Comment by leviding** [comment]
感谢指出。经查证，此处确实存在问题，英文原版原来存在问题，现已修复，详见 [fix debounce](https://github.com/javascript-tutorial/en.javascript.info/commit/cd5a7e451fdc9d681d8ffe000b81b17ddf52ac38#diff-6b4feed39a2a3ee8082f5528f764cadf)。

现本项目已根据您的提醒进行了修复，感谢 👍 如果发现其他问题，欢迎继续指出，大家一起让教程越来越好～
