### ISSUE TITLE
一处笔误

### ISSUE THREAD

**Issue by ArvineKwok** [javascript-tutorial/zh.javascript.info#761]
[表单属性和方法](https://zh.javascript.info/form-elements)一节中,“表单元素——input和textarea”的第一句话
> 我们可以通过 input.value（字符串）或 input.checked（布尔值）来访问复选框（cjeckbox）中的它们的 value。

复选框checkbox打成了cjeckbox。

**Comment by leviding** [comment]
感谢指出，以进行了修复，详见 [Fix minor typo error](https://github.com/javascript-tutorial/zh.javascript.info/commit/df14971e16e5b19f93e262824d19d8311aa874f7)。如果发现其他问题，欢迎继续指出 ❤️
