### ISSUE TITLE
Typo error of BigInt

### ISSUE THREAD

**Issue by willnotlazy** [javascript-tutorial/zh.javascript.info#784]
数据类型/BigInt类型中的number类型不能小于错误，原文为 -(-2^53 - 1)[url](https://github.com/javascript-tutorial/zh.javascript.info/blob/master/1-js/02-first-steps/05-types/article.md)

**Comment by leviding** [comment]
<img width="1029" alt="Screen Shot 2020-07-06 at 2 33 16 PM" src="https://user-images.githubusercontent.com/26959437/86562687-b0796700-bf95-11ea-82a6-0888b8daf2ce.png">
<img width="1038" alt="Screen Shot 2020-07-06 at 2 33 27 PM" src="https://user-images.githubusercontent.com/26959437/86562701-b5d6b180-bf95-11ea-8711-c4d0866fdcd9.png">
请问是指哪里有问题？

**Comment by leviding** [comment]
可以优化翻译，表述成：无法代表大于 xxx 或小于 xxx 的数字。但是你所说的错误是指什么？

其实 -(-2^53 - 1) 就是正数了吧，应该修改为：或小于 (-2^53 - 1) 的数字。

**Comment by leviding** [comment]
https://github.com/javascript-tutorial/en.javascript.info/pull/1995

**Comment by leviding** [comment]
Related commit: https://github.com/javascript-tutorial/zh.javascript.info/commit/f9800f8bba845115f9d2498f85102372a13245bf

**Comment by leviding** [comment]
Solved, thanks.
