### ISSUE TITLE
这个值名称是不有问题

### ISSUE THREAD

**Issue by hemingyang** [javascript-tutorial/zh.javascript.info#788]
![image](https://user-images.githubusercontent.com/28049728/87133683-411fb200-c2ca-11ea-8029-ea330e5cd1cf.png)

**Comment by leviding** [comment]
欢迎提问。这个不是值，falsy 和 truthy 是两个形容词，描述两类值。false 和 true 只是这两类值中的一个例子。

如果明白了可以关闭 issue，不明白可追问。
