### ISSUE TITLE
翻译中的一个错别字

### ISSUE THREAD

**Issue by OriX0** [javascript-tutorial/zh.javascript.info#790]
章节：函数进阶内容---旧时的 "var"
文章节点：IIFE
错误点：该节点第三个代码块后的 告 字应该为 该 字  >因此，需要使用圆括号把**告**函数表达式包起来，以告诉 JavaScript，这个函数是在另一个表达式的上下文中创建的，因此它是一个函数表达式：它不需要函数名，可以立即调用。

**Comment by leviding** [comment]
@OriX0 这样说很难看出来哪里有错误，能否提个 pull request？

**Comment by leviding** [comment]
Fixed in https://github.com/javascript-tutorial/zh.javascript.info/commit/b49b203cb2b3db32e08e2bc01737a774db0f72f4 right?

**Comment by leviding** [comment]
Thanks a lot @OriX0
