### ISSUE TITLE
需要跟进更新的部分

### ISSUE THREAD

**Issue by leviding** [javascript-tutorial/zh.javascript.info#798]
- [x] Update some chapters to [Jul 17, 2020] Part-4 https://github.com/javascript-tutorial/zh.javascript.info/pull/768 @MartinsYong in https://github.com/javascript-tutorial/zh.javascript.info/pull/801
- [x] Update some chapters to [Jul 17, 2020] Part-5 https://github.com/javascript-tutorial/zh.javascript.info/pull/794
- [x] Update some chapters to [Jul 17, 2020] Part-6 https://github.com/javascript-tutorial/zh.javascript.info/pull/795 @BillChen2K in https://github.com/javascript-tutorial/zh.javascript.info/pull/804
- [x] Update some chapters to [Jul 17, 2020] Part-7 https://github.com/javascript-tutorial/zh.javascript.info/pull/796 @BillChen2K in https://github.com/javascript-tutorial/zh.javascript.info/pull/807

详见对应的 PR。

**Comment by BillChen2K** [comment]
Translating Part-7

**Comment by leviding** [comment]
> Translating Part-7

Get it.
