### ISSUE TITLE
括号不匹配

### ISSUE THREAD

**Issue by OriX0** [javascript-tutorial/zh.javascript.info#800]
[贪婪量词和惰性量词 任务第一题](https://zh.javascript.info/regexp-greedy-and-lazy#dui-yu-dd-de-pi-pei) 部分 
  对于 /d+? d+?/ 的匹配
`"123 456".match(/\d+? \d+?/g) );`  括号不匹配 
多出一个括号 应该为
`"123 456".match(/\d+? \d+?/g) ;`
猜测原来前面应该有 alert

**Comment by leviding** [comment]
感谢提出，这里是没有 alert 的，至于是否错误，待确认，确认后在本 issue 给予反馈。

**Comment by leviding** [comment]
感谢，已修正，加了一个 alert。

Commit: https://github.com/javascript-tutorial/zh.javascript.info/commit/8d7a9cda95f4589f110fe3ffc7c435a46af25ed5
