### ISSUE TITLE
属性描述符中的configurable设置为false后的描述错误

### ISSUE THREAD

**Issue by kevinJser** [javascript-tutorial/zh.javascript.info#813]
属性描述符的[[configurable]]设置为false后，“不能将 writable: false 修改为 true（反之亦然）“。描述有误，经过自己尝试，当[[configurable]]设置为false后， [[writable]]不能从false修改为true，但是可以从true修改为false。

**Comment by leviding** [comment]
这个是译者翻译问题，将 ...work 翻译成反之亦然，整个教程有好几处反之亦然，需要全都检查核验一遍，感谢提出此问题 👍

**Comment by leviding** [comment]
经查证，本教程一共七处反之亦然，而你所指出的这个是翻译问题，其它的均没问题。非常感谢，已修正！

**Comment by leviding** [comment]
Commit: https://github.com/javascript-tutorial/zh.javascript.info/commit/56741ba49938e1ff50754d9aaec9fad2567d467a
