### ISSUE TITLE
关于更新问题

### ISSUE THREAD

**Issue by pasan26** [javascript-tutorial/zh.javascript.info#824]
不知道管理人员有没有一个好的方式，每次在网页上提示一些每次更新所提交的内容。
在网站上能看到最近一次更新的日期，但是具体哪些内容更新了，不是很明确，不知道可否改进一下。
辛苦了， 感谢

**Comment by leviding** [comment]
首先非常感谢你的建议：

目前的想法是，如果像 Git 的 commit 那样特别详细的提示，会比较难看。我觉得每次进行更新后，出一个更新日志怎么样？指出大致更新了哪些内容，可以使项目更完善，也方便读者们知道近期有哪些更新可以关注。
