### ISSUE TITLE
运算符优先级数字与MDN上不一致

### ISSUE THREAD

**Issue by A-aronYang** [javascript-tutorial/zh.javascript.info#825]
教程上的表格

优先级 | 名称 | 符号
-- | -- | --
… | … | …
17 | 一元加号 | +
17 | 一元负号 | -
16 | 求幂 | **
15 | 乘号 | *
15 | 除号 | /
13 | 加号 | +
13 | 减号 | -
… | … | …
3 | 赋值符 | =
… | … | …

Mozilla上的 的 优先级表

优先级 | 名称 | 符号
-- | -- | --
… | … | …
17 | 后置递增 | ...++
17 | 前置递增 | ++...
16 | 一元加号 | +
16 | 一元负号 | -
15 | 求幂 | **
14 | 乘号 | *
14 | 除号 | /
13 | 加号 | +
13 | 减号 | -
… | … | …
3 | 赋值符 | =
… | … | …

**Comment by leviding** [comment]
感谢提出问题，教程这里是没有问题的，你看的 MDN 应该是中文版的吧，中文版有问题，应该去看英文版：

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

**Comment by A-aronYang** [comment]
哦！非常感谢&nbsp;

&nbsp;


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LeviDing"<notifications@github.com&gt;; 
发送时间: 2020年9月16日(星期三) 上午10:05
收件人: "javascript-tutorial/zh.javascript.info"<zh.javascript.info@noreply.github.com&gt;; 
抄送: "JayV"<459852675@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [javascript-tutorial/zh.javascript.info] 运算符优先级数字与MDN上不一致 (#825)





 
感谢提出问题，教程这里是没有问题的，你看的 MDN 应该是中文版的吧，中文版有问题，应该去看英文版：
 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence
