### ISSUE TITLE
函数默认值部分的内容

### ISSUE THREAD

**Issue by A-aronYang** [javascript-tutorial/zh.javascript.info#826]
教程这段
例如，之前提到的函数 `showMessage(from, text)` 可以只使用一个参数调用：

```javascript
showMessage("Ann");
```

那不是错误，这样调用将输出 `"Ann: undefined"`。
------

根据前文应该是`"*Ann*: undefined"`吧

**Comment by leviding** [comment]
Related: https://github.com/javascript-tutorial/en.javascript.info/pull/2123
