### ISSUE TITLE
“DOM树“ 一节中有个不起眼的小错误

### ISSUE THREAD

**Issue by czpcalm** [javascript-tutorial/zh.javascript.info#829]
文章地址：https://zh.javascript.info/dom-nodes
这一节举了很多DOM树的例子，在展示DOM树的时候提醒读者注意文本节点中的换行 ↵ 和空格 ␣ ，它正确标出了空白文本节点的空格数了换行符，但是却漏了带有文本内容的文本节点中的空格和换行。
比如第一个例子中，有一个“#text: The truth about elk.”的文本节点，但是我测试的时候，节点的nodeValue值为：“↵␣␣The truth about elk.↵”前后有空白的。
本来不是什么大问题，不过文中强调这两个字符，就应该在所有地方都注意一下，所以才提出来。

**Comment by leviding** [comment]
感谢提出，这是一个问题，先排着待处理

**Comment by leviding** [comment]
感谢指出，正在处理中…

**Comment by songhn233** [comment]
https://github.com/javascript-tutorial/engine/commit/0eca159f2553da8a524419a49ebeb28b33755495 Now fixed.

![image](https://user-images.githubusercontent.com/47357585/141644136-fcd406d8-e2a9-419d-9754-4d484eb2d0aa.png)
