### ISSUE TITLE
杂项的Proxy 和 Reflect

### ISSUE THREAD

**Issue by codesyofo** [javascript-tutorial/zh.javascript.info#833]
[Proxy 和 Reflect](https://zh.javascript.info/proxy)
对于 `trap` `traps` 的翻译为 **陷阱** 看的一脸懵，建议替换为 **捕捉** **捕捉器**

机翻的过分了，查下资料也不至于翻成陷阱，

[MDN参考](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Proxy)

**Comment by leviding** [comment]
首先非常感谢您的提议，我们会谨慎考虑并进行修改。

但是请不要无脑喷上来就说机翻的过分，你机翻成这个水平试试？

另外，MDN 在翻译 Proxy 的时候，有的章节也将其翻译成陷阱，例如：https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler

MDN 中文版是开源的项目，大家都可以参与，请不要把它当作权威。

**Comment by leviding** [comment]
Resolved in https://github.com/javascript-tutorial/zh.javascript.info/pull/835
