### ISSUE TITLE
关于 类继承 一章的一个翻译问题

### ISSUE THREAD

**Issue by HsiaoYukun** [javascript-tutorial/zh.javascript.info#838]
[类继承 - 重写类字段: 一个棘手的注意要点](https://zh.javascript.info/class-inheritance#zhong-xie-lei-zi-duan-yi-ge-ji-shou-de-zhu-yi-yao-dian)中的一句：
> 在基类（还未继承任何东西的那种）被构造前初始化。

对应原文（[地址](https://javascript.info/class-inheritance#super-internals-homeobject)）是：
> Before constructor for the base class (that doesn’t extend anything),

翻译为 “对于基类（还未继承任何东西的那种），在构造函数调用前初始化” 是否更为妥当？

**Comment by leviding** [comment]
感谢指出，已优化翻译 👍
