### ISSUE TITLE
“深入理解箭头函数”一节，建议优化表达

### ISSUE THREAD

**Issue by ChenZhenshuo** [javascript-tutorial/zh.javascript.info#844]
箭头函数也没有 arguments 变量 => 箭头函数也没有 **自己的（或者说本作用域的）**arguments 变量

限定词有助于理解，箭头函数中也可以使用arguments，只是来自父

**Comment by leviding** [comment]
如果这样修改，那前面的箭头函数没有 this 是不是也要改成箭头函数没有自己的 this 呢？其实我觉得有些画蛇添足，没有就是没有，但是不代表在内部不能使用。而且下面的示例已经有相关说明代码了，也就是在箭头函数中使用了 arguments。

暂时不修改哈，欢迎继续讨论。
