### ISSUE TITLE
输入应考虑输入含空格的字符串

### ISSUE THREAD

**Issue by KINGZJS** [javascript-tutorial/zh.javascript.info#850]
Location : 数据类型 > 数组 > 任务（输入数字求和）> 解决方案
let value = prompt("A number please?", 0).trim();//**添加trim(), 避免输入含空格的字符串转化为0后插入到数组中。**

**Comment by leviding** [comment]
谢谢指出。

这题中已经说明：

P.S. `0` 是有效的数字，不要因为是 `0` 就停止问询。

其实这个题就是按照题干要求做就行，即使有带有空格的字符串被输入，是会被存入数组，但是没有影响写这题，也符合题干要求。还有一点就是，在这里用这个方法，因为还没学到，新手会有疑问和挫败感。

综上，保持现有答案。
