### ISSUE TITLE
数组方法那一章有个地方false写成了falsy

### ISSUE THREAD

**Issue by millnasis** [javascript-tutorial/zh.javascript.info#856]
介绍find和findindex那部分
![QQ图片20201202193358](https://user-images.githubusercontent.com/70905899/100861552-58f40e80-34d5-11eb-8f27-e16bfe79ba98.png)

**Comment by leviding** [comment]
感谢指出，这里已经优化为：对于假值（falsy）的情况，则返回 undefined。

这里不是 false，而是 falsy 值，这种值包括 0，''，false，null 等。

**Comment by leviding** [comment]
Commit: https://github.com/javascript-tutorial/zh.javascript.info/commit/023bca491dec16101ae4a35f133e194f6ec3c27f
