### ISSUE TITLE
1-js/02-first-steps/16-function-expressions：文字和语序的小错误

### ISSUE THREAD

**Issue by ATaoyoyo** [javascript-tutorial/zh.javascript.info#858]
目标章节：1-js/02-first-steps/16-function-expressions/

多了一个`的`字，在135行附近：
![image](https://user-images.githubusercontent.com/39755480/101322558-3467b000-38a2-11eb-9d3e-9fa5229b1140.png)

语序应该为：`则以下代码不能如愿工作`，在244行附近：
![image](https://user-images.githubusercontent.com/39755480/101322797-945e5680-38a2-11eb-8321-872d9b82ae11.png)

水平有限，就不重复PR了。感谢开源！

**Comment by leviding** [comment]
感谢指出和 PR，已合并。
