### ISSUE TITLE
旧时的"var“错误

### ISSUE THREAD

**Issue by Erica-hy** [javascript-tutorial/zh.javascript.info#863]
”如果一个代码块位于函数内部，那么 var 声明的变量的作用域将为函数作用域：“ 中的代码：

![image](https://user-images.githubusercontent.com/48206842/101889456-60549f80-3bda-11eb-87da-a09074f44b2f.png)

这里不是 works。

**Comment by MartinsYong** [comment]
这注释意思应该是“正常运行（没有错误）”，而不是打印结果。稍后我们会作出修订，感谢您的反馈~

**Comment by leviding** [comment]
已将 works 翻译为能正常工作，感谢指出，详见：https://github.com/javascript-tutorial/zh.javascript.info/blob/master/1-js/06-advanced-functions/04-var/article.md
