### ISSUE TITLE
关于 JavaScript 基础知识——值的比较中，希望更详细地讲解为什么 null==0 为 false

### ISSUE THREAD

**Issue by keepgoodfeeling** [javascript-tutorial/zh.javascript.info#864]
为什么null==0 为false？
原文中解释的不够清楚；希望可以优化一下，
如下是 “==”比较值的算法：

The comparison x == y, where x and y are values, produces true or false.

如果x不是正常值（比如抛出一个错误），中断执行。
如果y不是正常值，中断执行。
如果Type(x)与Type(y)相同，执行严格相等运算x === y。
如果x是null，y是undefined，返回true。
如果x是undefined，y是null，返回true。
如果Type(x)是数值，Type(y)是字符串，返回x == ToNumber(y)的结果。
如果Type(x)是字符串，Type(y)是数值，返回ToNumber(x) == y的结果。
如果Type(x)是布尔值，返回ToNumber(x) == y的结果。
如果Type(y)是布尔值，返回x == ToNumber(y)的结果。
如果Type(x)是字符串或数值或Symbol值，Type(y)是对象，返回x == ToPrimitive(y)的结果。
如果Type(x)是对象，Type(y)是字符串或数值或Symbol值，返回ToPrimitive(x) == y的结果。
return false。

**Comment by MartinsYong** [comment]
您好，此 repo 是对 [英文版](https://github.com/javascript-tutorial/en.javascript.info) 进行翻译的，如对原文内容有建议，欢迎到此英文 repo 提反馈，感谢~

**Comment by leviding** [comment]
![image](https://user-images.githubusercontent.com/26959437/121025636-f52a0580-c7d7-11eb-8ec9-984bef651983.png)

文中的解释如上图，使用很简短的文字描述了本文中对应示例所涉及的知识点。如果按照您给出的那种解释，可能过于繁杂，不适合放在此处，会让人觉得内容过多难以记住。所以暂时保持原样，感谢提出本 issue。
