### ISSUE TITLE
5.4 章节数组中有一个 typo error

### ISSUE THREAD

**Issue by FlightChen** [javascript-tutorial/zh.javascript.info#873]
5.4章节 数组 toString小节中发现一个小错误
[https://zh.javascript.info/array#tostring](url)

### 原文
`alert( [] + 1 ); // "1"`
`alert( [1] + 1 ); // "11"`
`alert( [1,2] + 1 ); // "1,21"`
> 数组没有 Symbol.toPrimitive，也没有 valueOf，它们只能执行 toString 进行转换，所以这里 [] 就变成了一个空字符串，[1] 变成了 "1"，**_[1,2] 变成了 "1,2"_**。

上面粗斜体部分应该是
> [1,2]变成了"1,21"

**Comment by leviding** [comment]
你好，感谢提 issue，这里没有问题哈：

```js
alert( [1,2] + 1 ); // "1,21"
```

[1,2] 变成了 "1,2"，所以 [1,2] + 1 结果为 "1,21"
