### ISSUE TITLE
原型和继承章节 其他内建原型小结

### ISSUE THREAD

**Issue by baizuige** [javascript-tutorial/zh.javascript.info#875]
原文： 因此`Array.prototype` 变成了这个数组的 prototype
应该改成： 因此`Array.prototype` 变成了这个数组的 `[[prototype]]`

**Comment by leviding** [comment]
感谢，待安排时间核实修改。

**Comment by leviding** [comment]
内容链接：https://zh.javascript.info/native-prototypes#qi-ta-nei-jian-yuan-xing

这里指的是原型，不是 [[prototype]]
