### ISSUE TITLE
[构造器和操作符 "new"]中的“任何函数都可以通过 new 来运行”的描述不准确。

### ISSUE THREAD

**Issue by Nicklaus6** [javascript-tutorial/zh.javascript.info#876]
原文地址：https://zh.javascript.info/constructor-new#zong-jie
文中说到“任何函数都可以通过 new 来运行”。
应该是除了 **箭头函数** 外的所有函数，都可以通过 new  来进行。
例子：
```javascript
let a = x => x + 1;
new a();
// Uncaught TypeError: a is not a constructor
```
因此希望能够补充考虑箭头函数的情况：
箭头函数，没有自己的this，arguments，super或 new.target， 它**不能用作构造函数** 。

**Comment by leviding** [comment]
感谢，待安排时间核实修改。

**Comment by leviding** [comment]
英文版同步确认中：https://github.com/javascript-tutorial/en.javascript.info/pull/2619

**Comment by leviding** [comment]
已修正，感谢 ❤️  https://github.com/javascript-tutorial/zh.javascript.info/commit/9128948991d32601fb113dc5d4bc7556bcdd8e15
