### ISSUE TITLE
原型继承章节 任务解决方案 优化

### ISSUE THREAD

**Issue by Jarwu** [javascript-tutorial/zh.javascript.info#878]
原型继承章节最后一个任务：为什么两只仓鼠都饱了？https://zh.javascript.info/task/hamster-proto

该任务官方的第一种解决方案:` this.stomach = [food]`并不符合题目意图`this.stomach.push(food)`

下面是改善的解决方案
```
    eat(food) {
      this.stomach = [...this.stomach,food];
    }
```

**Comment by leviding** [comment]
感谢，待安排时间核实修改。

**Comment by leviding** [comment]
Thanks, may be more correct, but kind of diverts attention from important stuff =)

I'd better not make this code even a tiny bit more complex here.
