### ISSUE TITLE
函数进阶内容 6.2中获取对象副本，spread语法获取副本属于浅拷贝

### ISSUE THREAD

**Issue by xiaobai1035** [javascript-tutorial/zh.javascript.info#879]
发现个小问题，如题，原对象层级比较多时被修改，副本对应也会被修改

**Comment by leviding** [comment]
感谢，待安排时间核实修改。

**Comment by leviding** [comment]
Spread 语法获取对象确实属于浅拷贝，教程说：还记得我们 之前讲过的 Object.assign() 吗？使用 spread 语法也可以做同样的事情。

Object.assign() 做的是浅拷贝，spread 也是浅拷贝，这里没问题的哈。

![image](https://user-images.githubusercontent.com/26959437/111093214-53e23900-8573-11eb-8ff5-76e41fefdd60.png)

**Comment by leviding** [comment]
Related https://github.com/javascript-tutorial/zh.javascript.info/commit/94a929805a5390698fb207082e19528b92cc7441
