### ISSUE TITLE
Object（对象）：基础知识：垃圾回收 翻译错误

### ISSUE THREAD

**Issue by wine99** [javascript-tutorial/zh.javascript.info#882]
小标题“总结”的上面一段：“当然，除非这是一个纯粹的利益关系。我在下面给你提供了一些相关链接。”
原文：Unless, of course, it is a matter of pure interest, then there will be some links for you below.
翻译有误，可译为：“当然，除非你很感兴趣。我在下面给你提供了一些相关链接。”

**Comment by leviding** [comment]
感谢，待安排时间核实修改。

**Comment by leviding** [comment]
感谢，已修复！
