### ISSUE TITLE
Optional chaining '?.' 章节部分翻译待更新

### ISSUE THREAD

**Issue by hemuyao** [javascript-tutorial/zh.javascript.info#884]
在二级标题：Other variants: ?.(), ?.[] 的示例下面，英文部分是：

Here, in both lines we first use the dot (userAdmin.admin) to get admin property, because we assume that the user object exists, so it’s safe read from it.

Then ?.() checks the left part: if the admin function exists, then it runs (that’s so for userAdmin). Otherwise (for userGuest) the evaluation stops without errors.

而中文部分是：

在这两行代码中，我们首先使用点符号（user1.admin）来获取 admin 属性，因为用户对象一定存在，因此可以安全地读取它。

然后 ?.() 会检查它左边的部分：如果 admin 函数存在，那么就调用运行它（对于 user1）。否则（对于 user2）运算停止，没有错误。

不知道为什么，中文翻译中，将`userAddmin.admin`改成了`user1.admin`，将`userGuest`改成了`user2`，导致看的时候一头雾水。

**Comment by leviding** [comment]
不是翻译错了，是英文有更新。中文还没同步过来，等我抽时间处理哈~

**Comment by leviding** [comment]
已更正，感谢指出！
