### ISSUE TITLE
没找到 webWorker 和 requestIdleCallback，是否可以添加

### ISSUE THREAD

**Issue by 1850021148** [javascript-tutorial/zh.javascript.info#886]
电子书我才看一半，也不知道具体有没有这些，但是看了一下目录，并搜索一下，发现好像没有。
这些东西怎么说也是es标准的内容，如果没有的话，希望能加一下。
另外，这个网站很棒，祝你们做得越来越好！

**Comment by leviding** [comment]
中文版是根据英文版翻译优化，发现有需要加的内容会去先更新英文版然后同步到中文。本问题记下了，待安排时间跟进。谢谢~

**Comment by leviding** [comment]
在 https://zh.javascript.info/event-loop 页面最下方有提到 Web Worker，对于 requestIdleCallback 是一个实验中的 API，内容很少，类似的 API 也很多。

新增内容可以去英文版提 Pull Request，此处暂不做过多修改，感谢！
