### ISSUE TITLE
变量作用域和闭包这一节任务里面“ if 内的函数 “这个例子答案是错的

### ISSUE THREAD

**Issue by lz1012** [javascript-tutorial/zh.javascript.info#890]
变量作用域和闭包这一节任务里面“ if 内的函数 “这个例子答案是错的，
经过我的测试 是可以正常弹出 Hello, John

**Comment by lz1012** [comment]
[https://zh.javascript.info/closure#if-nei-de-han-shu](url)

**Comment by leviding** [comment]
本教程默认开启严格模式，你自己测试的时候没有开启，所以会认为是教程错了。

**Comment by lz1012** [comment]
谢谢，是的 我没开启，开启以后就可以了
