### ISSUE TITLE
可能是笔误？

### ISSUE THREAD

**Issue by wuyudi** [javascript-tutorial/zh.javascript.info#891]
https://zh.javascript.info/localstorage#jin-zi-fu-chuan

这章里面

```js
sessionStorage.user = JSON.stringify({name: "John"});
```

感觉应该是

```js
localStorage.user = JSON.stringify({name: "John"});
```

因为下文才提到 `sessionStorage`

> 如果是 typo，我就提 pr 了

**Comment by MartinsYong** [comment]
您好~我觉得问题不大。
具体以原文为准 <https://github.com/javascript-tutorial/en.javascript.info/blob/master/6-data-storage/02-localstorage/article.md>。您也可以到原文 repo 中提 PR。

**Comment by wuyudi** [comment]
https://github.com/javascript-tutorial/en.javascript.info/issues/2576 问了，其实没啥问题。

**Comment by wuyudi** [comment]
原文修了

**Comment by leviding** [comment]
已修复 https://github.com/javascript-tutorial/zh.javascript.info/commit/3767d053c4969a31b5a513f9611a326272408bd8 ，感谢 @wuyudi
