### ISSUE TITLE
变量

### ISSUE THREAD

**Issue by xiaohongcoder** [javascript-tutorial/zh.javascript.info#893]
https://zh.javascript.info/variables

页面底部的任务 ”给出正确的名字”

![image](https://user-images.githubusercontent.com/61079864/113483301-4fa39e80-94d5-11eb-91b2-6c5dbf6f38a1.jpeg)

**Comment by songhn233** [comment]
这是折叠区域，点击可以展开

**Comment by xiaohongcoder** [comment]
嗯？> 这是折叠区域，点击可以展开

**Comment by songhn233** [comment]
![image](https://user-images.githubusercontent.com/47357585/113504362-3567d000-956a-11eb-8fb7-6f55806715ae.png)

有什么问题吗？

**Comment by xiaohongcoder** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/47357585/113504362-3567d000-956a-11eb-8fb7-6f55806715ae.png)
> 
> 
> 
> 有什么问题吗？

奥，原来还可以二次展开呀![image](https://user-images.githubusercontent.com/61079864/113504471-da82a880-956a-11eb-9aaf-cf8cce0cbde7.jpeg)
