### ISSUE TITLE
基础运算符，数学

### ISSUE THREAD

**Issue by xiaohongcoder** [javascript-tutorial/zh.javascript.info#894]
[点击跳转](https://zh.javascript.info/operators)

自增/自减

![image](https://user-images.githubusercontent.com/61079864/113644196-c51a9500-96b6-11eb-94db-f3d402130a1b.jpeg)

**Comment by xiaohongcoder** [comment]
> [点击跳转](https://zh.javascript.info/operators)
> 
> 自增/自减
> 
> ![image](https://user-images.githubusercontent.com/61079864/113644196-c51a9500-96b6-11eb-94db-f3d402130a1b.jpeg)

![image](https://user-images.githubusercontent.com/61079864/113644514-85a07880-96b7-11eb-981c-600331f16f28.jpeg)

**Comment by xiaohongcoder** [comment]
![image](https://user-images.githubusercontent.com/61079864/113644568-a23cb080-96b7-11eb-966f-2fd655b9c520.jpeg)

**Comment by songhn233** [comment]
不太懂你的意思

原文的意思是
```js
let counter = 1;
alert( 2 * counter++ );
```
与
```js
let counter = 1;
alert( 2 * counter );
counter++;
```
两种写法等价

而第二种写法可读性更好

**Comment by xiaohongcoder** [comment]
我理解的对吗![image](https://user-images.githubusercontent.com/61079864/113703373-53ba0100-970d-11eb-998a-f84713547edf.jpeg)

**Comment by songhn233** [comment]
后置自加虽然优先级比普通运算符高，但是是先计算出表达式的值再进行自加的。前置自加才是你理解的这种行为。

**Comment by xiaohongcoder** [comment]
谢谢大师，我悟了。
