### ISSUE TITLE
QR Code in zh.javascript.info need update

### ISSUE THREAD

**Issue by leviding** [javascript-tutorial/zh.javascript.info#896]
<img width="952" alt="Screen Shot 2021-04-09 at 3 48 40 PM" src="https://user-images.githubusercontent.com/26959437/114149202-3bd0c000-994d-11eb-85aa-0d6c9868fdcc.png">

@iliakan  QR Code of WeChat need update:

This is the new QR code:

![2020-07-28 QQ   WeChat Group Info of javascript info](https://user-images.githubusercontent.com/26959437/114149468-84887900-994d-11eb-9d71-92dc6ee596b2.png)

**Comment by iliakan** [comment]
Only this image?

**Comment by iliakan** [comment]
Sorry for the delay. Please clear browser cache and check now.

**Comment by leviding** [comment]
Great, I have checked it, thanks!
