### ISSUE TITLE
元素大小和滚动章节 练习题配图错误

### ISSUE THREAD

**Issue by touryung** [javascript-tutorial/zh.javascript.info#897]
元素大小和滚动章节的第三个任务：将小球置于区域中心 [https://zh.javascript.info/task/put-ball-in-center](https://zh.javascript.info/task/put-ball-in-center)

解决方案中的第二张配图，应该是将小球的左上边缘居于区域中间

具体原因暂时没发现，初步猜测是命名冲突

**Comment by MartinsYong** [comment]
看着是加载时序问题，field 没渲染出来，所以获取到的 clientWidth/clientHeight 为 0。

**Comment by leviding** [comment]
已修复 https://github.com/javascript-tutorial/zh.javascript.info/commit/5c81e6476bb18d85922a339d09b08b34d4b149e0

等待上游更新 https://github.com/javascript-tutorial/en.javascript.info/pull/3282

**Comment by leviding** [comment]
已修复

![image](https://user-images.githubusercontent.com/26959437/204134999-b48e4fa5-9aa9-4009-aa83-72ccba9adb09.png)

等待上游更新：https://github.com/javascript-tutorial/en.javascript.info/pulls
