### ISSUE TITLE
字符串－特殊字符中的 \xXX 描述模糊

### ISSUE THREAD

**Issue by uwjiaoxing** [javascript-tutorial/zh.javascript.info#902]
`\xXX` 转义字符范围是 ISO-8859-1 字符集，码位超过 `0xFF` 的第三位不会被转义。

比如 `\u0100` 的对应的字符是 `Ā` ，而 `\x100` 会显示 `0`，实际转义的是 `\x10` ，第二个`0` 是原样显示的。

文中描述感觉有点不是很清楚。

**Comment by leviding** [comment]
@uwjiaoxing 请问具体是哪个章节的描述，能提供一个链接吗

**Comment by leviding** [comment]
你好，感谢提 issue。这里 `\xXX` 已经表示限定 `\x` 后只有两个字符，不会出现第三个字符的情况，所以不存在你说的那个问题。这里暂不做更改哈。
