### ISSUE TITLE
原文中的一处16进制描述错误(an error with hexadecimal numbers in the original article)

### ISSUE THREAD

**Issue by ViavaCos** [javascript-tutorial/zh.javascript.info#903]
描述：
这个应该是原文中的一处错误，但是在翻译的过程中没有人发现...导致多个版本中都存在这个错误。16进制数的范围是0-9或A-F(a-f)
This is supposed to be an error in the original article, but no one found it during the translation... This causes this error to exist in multiple versions. The range of hexadecimal numbers is 0-9 or A-F(a-f).

Path:
https://zh.javascript.info/regexp-unicode

ZH: 
举个例子，让我们来查找 16 进制数字，写作 xFF 其中 F 是一个 16 进制的数字（0…1 或者 A…F）。

JA:
例えば、xFF のようにして書かれた16進数を探しましょう。ここで F は16進数値です(0…1 or A…F)。

EN:
For instance, let’s look for hexadecimal numbers, written as xFF, where F is a hex digit (0…1 or A…F).

...

**Comment by ViavaCos** [comment]
如果长时间没有修复的话，我有时间了会尝试提交PR帮忙修复一下的。
( If it hasn't been repaired for a long time, I will try to submit PR to help repair it when I have time. )

**Comment by MartinsYong** [comment]
是少了小写（a-f）吗？我觉得没关系呀

**Comment by leviding** [comment]
感谢指出，已将 16 进制数的范围为 0...1 或 A...F 更正为 0...9 或 A...F，感谢指出。

**Comment by leviding** [comment]
英文版修改：https://github.com/javascript-tutorial/en.javascript.info/pull/2621
中文版修改：https://github.com/javascript-tutorial/zh.javascript.info/commit/32625d59b7f1a2535b32580976518a132c93e856
