### ISSUE TITLE
严格模式下Uncaught TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by shaoshenchen** [javascript-tutorial/zh.javascript.info#904]
[遍历：forEach](https://zh.javascript.info/array-methods#bian-li-foreach) 部分的代码
```js
// 对每个元素调用 alert
["Bilbo", "Gandalf", "Nazgul"].forEach(alert);
```
在严格模式下运行会报错 **Uncaught TypeError: Cannot read property 'forEach' of undefined**。
但是在 [我们应该使用 “use strict” 吗？](https://zh.javascript.info/strict-mode#wo-men-ying-gai-shi-yong-usestrict-ma) 中提到
> 本教程的所有例子都默认采用严格模式，除非特别指定（非常少）。

说明这段代码应该在严格模式下也能运行。

后面发现把数组和方法分开写没问题
```js
"use strict"
let arr = ["Bilbo", "Gandalf", "Nazgul"];

arr.forEach(item => alert(item));
```

想明白这其中的原因是什么？

**Comment by leviding** [comment]
因为，"use strict" 后面需要加分号，否则会被认为是字符串：

```js
"use strict"
["Bilbo", "Gandalf", "Nazgul"].forEach(alert);
```

会被认为是：

```js
"use strict"["Bilbo", "Gandalf", "Nazgul"].forEach(alert);
```

所以报错。

而下面这种：

```js
"use strict"
let arr = ["Bilbo", "Gandalf", "Nazgul"];

arr.forEach(item => alert(item));
```

因为有 let 声明一个数组，所以解析代码的时候，知道这是一个新的语句，所以没问题。

**Comment by leviding** [comment]
如果还有问题，可以艾特我哈~
