### ISSUE TITLE
Edgy应改为Edge

### ISSUE THREAD

**Issue by shaoshenchen** [javascript-tutorial/zh.javascript.info#907]
地址：[元素大小和滚动](https://zh.javascript.info/size-and-scroll#bu-yao-cong-css-zhong-huo-qu-widthheight)
`在桌面 Windows 操作系统上，Firefox、Chrome、Edgy 都为滚动条保留了空间。` 应改为 `在桌面 Windows 操作系统上，Firefox、Chrome、Edge都为滚动条保留了空间。`

**Comment by leviding** [comment]
Solved. Thanks a lot.

Commit: https://github.com/javascript-tutorial/zh.javascript.info/commit/0d105e586aa2d17ba30af92b8b3c76cf3dc9a3f5
