### ISSUE TITLE
在 《构造器和操作符 "new"》 一节增加一行注释

### ISSUE THREAD

**Issue by YanJinyang** [javascript-tutorial/zh.javascript.info#908]
function User(name) {
// this = {};（隐式创建）
// this.\_\_proto\_\_ = User.prototype;
// 添加属性到 this
this.name = name;
this.isAdmin = false;

// return this;（隐式返回）
}
这里再加一个 this.\_\_proto\_\_ = User.prototype;这个对于后面原型的理解也很有帮助

**Comment by leviding** [comment]
感谢提出 issue，本节内容只是学习 构造器和操作符 "new"，不探讨原型相关内容，所以在这里提原型会比较突兀，原型的内容会在对应的章节做详细介绍。
