### ISSUE TITLE
一处翻译的错别字

### ISSUE THREAD

**Issue by Blackmegg1** [javascript-tutorial/zh.javascript.info#910]
[搜索：getElement*，querySelector*](https://github.com/javascript-tutorial/zh.javascript.info/edit/master/2-ui/1-document/04-searching-elements-dom/article.md) 177行——而你依然可以在**就**脚本中找到这些方法。

**Comment by KimYangOfCat** [comment]
直接修改后提交 PR 也许会是更好的选择

**Comment by leviding** [comment]
我这几天修改

**Comment by leviding** [comment]
Fixed in https://github.com/javascript-tutorial/zh.javascript.info/commit/e6c2bab9a6384420c539a697e4a54379d7d31198
