### ISSUE TITLE
数据类型-解构赋值 排版有误

### ISSUE THREAD

**Issue by zhongfly** [javascript-tutorial/zh.javascript.info#920]
https://zh.javascript.info/destructuring-assignment#shu-zu-jie-gou
其中“交换变量值的技巧”这一提示后的2段应该也是该提示的内容，却被错误的放在框外。

![image](https://user-images.githubusercontent.com/11155705/121804909-5724b800-cc7b-11eb-8c07-a71c28764ae4.png)

**Comment by leviding** [comment]
感谢指出问题并修改。
