### ISSUE TITLE
数据类型-日期和时间 new Date(milliseconds)的描述问题

### ISSUE THREAD

**Issue by zhongfly** [javascript-tutorial/zh.javascript.info#923]
原文如下

> new Date(milliseconds)
> 创建一个 Date 对象，其时间等于 1970-01-01 00:00:00 UTC+0 **再过一毫秒**（1/1000 秒）。

这个再过一毫秒是笔误吧？

**Comment by leviding** [comment]
Create a Date object with the time equal to number of milliseconds (1/1000 of a second) passed after the Jan 1st of 1970 UTC+0.

创建一个 Date 对象，其时间等于 1970 年 1 月 1 日 UTC+0 之后经过的毫秒数（1/1000 秒）。

**Comment by leviding** [comment]
Thanks, fixed in https://github.com/javascript-tutorial/zh.javascript.info/commit/eb4dbe2698dfc176f837b5b9dea872c59af09063
