### ISSUE TITLE
UI事件>键盘:keydown 和 keyup>默认行为:  dom0事件使用的return写法,建议说明一下.

### ISSUE THREAD

**Issue by aotushi** [javascript-tutorial/zh.javascript.info#924]
`<script>
function checkPhoneKey(key) {
  return (key >= '0' && key <= '9') || key == '+' || key == '(' || key == ')' || key == '-';
}
</script>
<input onkeydown="return checkPhoneKey(event.key)" placeholder="Phone, please" type="tel">`

**建议**: `onkeydown="return checkPhoneKey(evnet.key)"`中事件中使用的return和不使用return,  建议添加说明.

**Comment by leviding** [comment]
Related: https://github.com/javascript-tutorial/en.javascript.info/issues/2641

**Comment by iliakan** [comment]
请再检查英文文本

**Comment by leviding** [comment]
已更新，感谢 https://github.com/javascript-tutorial/zh.javascript.info/commit/a3e0d0e84efb037fbbcb9faea4dd86e093d2697b
