### ISSUE TITLE
浏览器：文档，事件，接口-Document 任务2中的错误

### ISSUE THREAD

**Issue by zhongfly** [javascript-tutorial/zh.javascript.info#926]
https://github.com/javascript-tutorial/zh.javascript.info/blob/master/2-ui/1-document/03-dom-navigation
任务2 兄弟节点问题 的解决方案

> 1.是的，这是真的。elem.lastChild 就是最后一个**元素**，它没有 nextSibling。

`elem.lastChild` 应该是最后一个**节点**吧？[MDN](https://developer.mozilla.org/zh-CN/docs/Web/API/Node/lastChild)

**Comment by leviding** [comment]
Thanks, fixed in https://github.com/javascript-tutorial/zh.javascript.info/commit/821fc91dc0d92eecfae0f9537605ca8d044002fb
