### ISSUE TITLE
一个用词准确的小建议

### ISSUE THREAD

**Issue by WangShuoran** [javascript-tutorial/zh.javascript.info#932]
https://zh.javascript.info/function-expressions
注意，最后一行代码并不会运行函数，因为 sayHi 后没有括号。在**其他**编程语言中，只要提到函数的名称都会导致函数的调用执行，但 JavaScript 可不是这样。
问题：
这里用其他显得js比较异类，但是其实有很多都是需要后加括号来执行，如Python、C，我建议稍微修改一下

**Comment by leviding** [comment]
非常感谢宝贵意见，已将「其他」修改为「某些」https://github.com/javascript-tutorial/zh.javascript.info/commit/eb3185bc7d03c45c99ce37eb99c011c4e4d23df3
