### ISSUE TITLE
数字类型章节任务 6 描述的标点问题

### ISSUE THREAD

**Issue by wordpure** [javascript-tutorial/zh.javascript.info#934]
[数字类型 - 从 min 到 max 的随机整数](https://zh.javascript.info/number#cong-min-dao-max-de-sui-ji-zheng-shu)

任务介绍第一段，参数 min 与 max 之间用了中文逗号分隔，应改为英文逗号。

![图片](https://user-images.githubusercontent.com/68013962/127456399-077ef4c8-bcbd-43d4-95bc-c69b1ee7cd6e.png)

**Comment by leviding** [comment]
Thanks a lot, fixed https://github.com/javascript-tutorial/zh.javascript.info/commit/56bd0906d8c1c588797a310103986aadb280b482
