### ISSUE TITLE
5.8中WeakSet 追踪访问网站用户的例子注释存疑

### ISSUE THREAD

**Issue by wanghongxuok** [javascript-tutorial/zh.javascript.info#937]
let visitedSet = new WeakSet();

let john = { name: "John" };
let pete = { name: "Pete" };
let mary = { name: "Mary" };

visitedSet.add(john); // John 访问了我们
visitedSet.add(pete); // 然后是 Pete
visitedSet.add(john); // John 再次访问

// visitedSet 现在有两个用户了

// 检查 John 是否来访过？
alert(visitedSet.has(john)); // true

// 检查 Mary 是否来访过？
alert(visitedSet.has(mary)); // false

john = null;

// visitedSet 将被自动清理               ### **//请确认这句注释是否存在问题,这里应是john被自动清理**********

**Comment by leviding** [comment]
感谢指出。此处描述是有一些歧义，文中表述的意思是，visitedSet 会被自动清理，不是指它被清除掉，而是自动清理掉其中失效的值。

因此，我已对文中内容进行了补充：visitedSet 将被自动清理(即自动清除其中已失效的值 john)

commit: https://github.com/javascript-tutorial/zh.javascript.info/commit/1f176fd5877f84fcf52151e499ef4c22a4776ed9

不知这样修改是否可以更清晰，如果还有更好的意见或建议，麻烦重新打开本 issue。
