### ISSUE TITLE
5.10解构赋值中可能的翻译错误

### ISSUE THREAD

**Issue by JunxiHe459** [javascript-tutorial/zh.javascript.info#944]
在5.10解构赋值的对象解构部分的第6处代码块中，
![image](https://user-images.githubusercontent.com/73581692/131254543-efbca896-4884-4fb7-85d2-f441207cc682.png)
第7行的注释原文为： // (whatever the result of prompt is)
这里翻译为：//（无论 prompt 的结果是什么）
我认为这不是一个比较准确的翻译。
我的建议是，翻译为：//（prompt 的结果）或者 //（prompt 的返回值）

如有错误，敬请谅解。

**Comment by leviding** [comment]
感谢指出，已修复！

Commit: https://github.com/javascript-tutorial/zh.javascript.info/commit/5e7c2cb7ee7c3612b6b5ff5aa47a1391335c803d
