### ISSUE TITLE
第一部分6.6函数对象，NFE,这一章中任务的第一题,题干中counter.decrease(value) 应该把 count 减 1,应没有value传参

### ISSUE THREAD

**Issue by wanghongxuok** [javascript-tutorial/zh.javascript.info#946]
任务
为 counter 添加 set 和 decrease 方法
重要程度: 5
修改 makeCounter() 代码，使得 counter 可以进行减一和设置值的操作：

counter() 应该返回下一个数字（与之前的逻辑相同）。
counter.set(value) 应该将 count 设置为 value。
counter.decrease(value) 应该把 count 减 1。                        _**//这里不应有value传参**_
查看沙箱中的代码获取完整使用示例。

P.S. 你可以使用闭包或者函数属性来保持当前的计数，或者两种都写。

打开带有测试的沙箱。

**Comment by leviding** [comment]
非常感谢，已修复！
