### ISSUE TITLE
6.3《变量作用域,闭包》章节中存在的问题

### ISSUE THREAD

**Issue by webapinewgamer** [javascript-tutorial/zh.javascript.info#947]
### 这是官方demo运行的效果截图
![image](https://user-images.githubusercontent.com/50972442/131362393-4947d773-7d2b-47ac-b48b-3285e1b11c00.png)

### 这是在chrome控制台中运行的效果截图

![image](https://user-images.githubusercontent.com/50972442/131362255-41c57fb0-cb21-4f57-8280-8a75984badde.png)

**Comment by songhn233** [comment]
文章中代码默认开启 'use strict' 严格模式，控制台中不会限制，所以结果有区别

**Comment by webapinewgamer** [comment]
> 文章中代码默认开启 'use strict' 严格模式，控制台中不会限制，所以结果有区别

感谢回答 是我疏忽了
