### ISSUE TITLE
数据类型->字符串->字符串是不可变的这块有个小问题

### ISSUE THREAD

**Issue by hello9102** [javascript-tutorial/zh.javascript.info#952]
let str = 'Hi';

str[0] = 'h'; // error
alert( str[0] ); // 无法运行

问题：只有在严格模式下会报错，不运行alert；如果是在非严格模式下，不会报错，alert的内容是H

**Comment by songhn233** [comment]
参加 [说明](https://zh.javascript.info/strict-mode)
![image](https://user-images.githubusercontent.com/47357585/133209362-3d099e08-d2fa-43b1-9bfc-47ee78a4ab95.png)

**Comment by hello9102** [comment]
看到后面都忘记前面这个了，好吧
