### ISSUE TITLE
5.5中的splice方法建议添加如果只有一个参数时的情况

### ISSUE THREAD

**Issue by hello9102** [javascript-tutorial/zh.javascript.info#953]
splice只有一个值时，从当前位置删除到数组末尾。
let arr=[1,2,3,4,5];
let num=arr.splice(1);
console.log(num,arr);//[2,3,4,5]  [1]
还有一个点是如果没有值被删除的话则返回空数组，否则返回被删除的值；

**Comment by leviding** [comment]
感谢提出建议。

针对 splice 只有第一个参数的情况，在教程中已做补充。

Commit: https://github.com/javascript-tutorial/zh.javascript.info/commit/c5be5e99ce08a7afc788f7fd18f07373e7beb6c3

针对如果没有值被删除时返回空数组，没有再作补充。文中已说“返回已被删除元素的数组”，也就包含了没有值被删除时返回空数组的情况，故不再赘述。
