### ISSUE TITLE
代码风格 一处笔误

### ISSUE THREAD

**Issue by vactiger** [javascript-tutorial/zh.javascript.info#954]
[代码风格](https://zh.javascript.info/coding-style#feng-ge-zhi-nan)的第一段

> 风格指南包含了“如果编写”代码的通用规则，

其中的「如果编写 」应为「如何编写」。

---

感谢作者及译者的努力，此书让我获益匪浅 🙂️

将持续反复阅读、学习此教程，若发现有误之处会尽自己的绵薄之力反馈，谢谢您。

**Comment by leviding** [comment]
非常感谢，已修复。

Commit: https://github.com/javascript-tutorial/zh.javascript.info/commit/777831ed144139d8fecaa121d9a8751f4914c334

如有发现问题，欢迎继续指出 👍

**Comment by leviding** [comment]
谢谢认可，一起加油！
