### ISSUE TITLE
[事件：change，input，cut，copy，paste] 章节中存在可能引起疑惑的代码内容

### ISSUE THREAD

**Issue by AnteeHub** [javascript-tutorial/zh.javascript.info#956]
## 来源
> zh.javascript.info/2-ui/4-forms-controls/3-events-change-input/article.md

### 说明
原文引文如下：
> 例如，下面的代码阻止了所有的这样的事件，并**显示**出了我们所尝试剪切/拷贝/粘贴的内容……

但在下方所显示的代码中，却没有能够在`alert`中显示出用户剪切、拷贝的内容，仅有粘贴的内容。

```html
<input type="text" id="input">
<script>
  input.oncut = input.oncopy = input.onpaste = function(event) {
    alert(event.type + ' - ' + event.clipboardData.getData('text/plain'));
    return false;
  };
</script>
```

### 说明配图
- 尝试复制文本框里的文字
![image](https://user-images.githubusercontent.com/55703989/136655916-c4d3e0aa-5b6b-4b97-857c-03bbac637eea.png)
- 尝试粘贴文字到文本框
![image](https://user-images.githubusercontent.com/55703989/136655954-c11b7a1a-ed3a-4312-82d4-7b6e7f25b71d.png)

## 解决 
下面的改进代码可以解决在`复制`和`粘贴`时，`alert`可以显示相应操作的文本内容：
```html
<input type="text" id="input" />
<script>
    input.oncut = input.oncopy = function (event) {
      event.clipboardData.setData('text/plain', event.target.value);
      alert(event.type + ' - ' + event.clipboardData.getData('text/plain'));
      return false;
    };
    input.onpaste = function (event) {
      alert(event.type + ' - ' + event.clipboardData.getData('text/plain'));
      return false;
    };
  </script>
```

## 补充
- 以上内容由于是在中文社区发现的，但本人又不是官方的维护者，所以希望从中文社区发出修改建议，并希望如果这部分意见被采纳后可以同步到其他语言的文档中。
- 对于初学者来说，有时候他们并不能很好的分辨出 `onpaste` 函数返回 `false` 的作用，建议添加相应的说明文字表示其和 `event.preventDefault()` 是等效的。

**Comment by leviding** [comment]
问题已修复，感谢各位！
