### ISSUE TITLE
【键盘：keydown 和 keyup】章节的部分问题

### ISSUE THREAD

**Issue by feihu233** [javascript-tutorial/zh.javascript.info#957]
首先，可以全局替换把“案件”改为“按键”
其次，#mo-ren-hang-wei 锚点下“输入手机号严格过滤器”的例子中，通过中文输入法输入汉字和英文字符不会受到过滤，希望增加关于这一点的说明。
详细叙述第二段。当我在该 input 中想输入英文字符（而那是被过滤的）时，我可以切换为中文键盘，输入英文字符后点击Enter将在输入法中缓存的英文字符直接放入 input 中。

**Comment by feihu233** [comment]
By the way dude, 默认行为(mo-ren-xing-wei)`s 3rd letter should be 'hang', not 'xing'. We call 银行(bank)`s 行 as 'hang'. 
顺带一提老哥，默认行为的行，中文拼音是 xing 而不是 hang，银行 bank 的行才读成 hang。

**Comment by songhn233** [comment]
> By the way dude, 默认行为(mo-ren-xing-wei)`s 3rd letter should be 'hang', not 'xing'. We call 银行(bank)`s 行 as 'hang'. 顺带一提老哥，默认行为的行，中文拼音是 xing 而不是 hang，银行 bank 的行才读成 hang。

实际上译者团队是不会有精力去维护标题对应的拼音的，这是 [engine](
https://github.com/javascript-tutorial/engine/blob/e16e28565ad071c4bb868e9fdfba0223d98de9cb/text-utils/transliterate/index.js#L21) 自动为锚点生成的有一定可读性的标题，大致通过 [limax](https://github.com/lovell/limax#readme) 来生成，这个是不要求准确性的。
