### ISSUE TITLE
Can we change Discord chat channel (English) into Chinese reader communication group？

### ISSUE THREAD

**Issue by leviding** [javascript-tutorial/zh.javascript.info#981]
![image](https://user-images.githubusercontent.com/26959437/146355467-443ad21e-0658-4fb8-be57-eade53cd8142.png)

Change "Discord Chat (English)" into  “前端学习交流群”

Icon: downloap [[png]](https://img.alicdn.com/imgextra/i2/O1CN01nbwGeU23zMJ1ZSDIX_!!6000000007326-2-tps-37-32.png), [[svg]](https://img.alicdn.com/imgextra/i2/O1CN01bzkoKN1ybTZcOHZ2N_!!6000000006597-55-tps-37-32.svg)

Svg code of icon:

```
<svg t="1639651128041" class="icon" viewBox="0 0 1170 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="3214" width="32" height="32"><path d="M331.429 263.429q0-23.429-14.286-37.715t-37.714-14.285q-24.572 0-43.429 14.571t-18.857 37.429q0 22.285 18.857 36.857t43.429 14.571q23.428 0 37.714-14t14.286-37.428zM756 553.143q0-16-14.571-28.572T704 512q-15.429 0-28.286 12.857t-12.857 28.286q0 16 12.857 28.857T704 594.857q22.857 0 37.429-12.571T756 553.143zM621.143 263.429q0-23.429-14-37.715t-37.429-14.285q-24.571 0-43.428 14.571t-18.857 37.429q0 22.285 18.857 36.857t43.428 14.571q23.429 0 37.429-14t14-37.428zM984 553.143q0-16-14.857-28.572T932 512q-15.429 0-28.286 12.857t-12.857 28.286q0 16 12.857 28.857T932 594.857q22.286 0 37.143-12.571T984 553.143zM832 326.286Q814.286 324 792 324q-96.571 0-177.714 44T486.57 487.143 440 651.429q0 44.571 13.143 86.857-20 1.714-38.857 1.714-14.857 0-28.572-0.857t-31.428-3.714-25.429-4-31.143-6-28.571-6L124.57 792l41.143-124.571Q0 551.429 0 387.429q0-96.572 55.714-177.715T206.571 82t207.715-46.571q100.571 0 190 37.714T754 177.429t78 148.857z m338.286 320.571q0 66.857-39.143 127.714t-106 110.572l31.428 103.428-113.714-62.285q-85.714 21.143-124.571 21.143-96.572 0-177.715-40.286T512.857 797.714t-46.571-150.857T512.857 496t127.714-109.429 177.715-40.285q92 0 173.143 40.285t130 109.715 48.857 150.571z" p-id="3215" fill="#c4433a"></path></svg>
```

---

![image](https://user-images.githubusercontent.com/26959437/146355510-a43663ee-7556-4fcf-b7a3-8d17dad1171d.png)
Can we change these two part into Chinese reader communication group？

**Comment by leviding** [comment]
@iliakan

**Comment by iliakan** [comment]
Yes, I already asked our designer to do that.

Best regards,
Ilya Kantor

**Comment by iliakan** [comment]
Does this look good?

![image](https://user-images.githubusercontent.com/349336/146729102-1e4658ed-d44f-4499-96c4-22809c6841ce.png)

**Comment by leviding** [comment]
> Does this look good?
> 
> ![image](https://user-images.githubusercontent.com/349336/146729102-1e4658ed-d44f-4499-96c4-22809c6841ce.png)

Great!

**Comment by leviding** [comment]
@iliakan  I recommend:
1. Change [Wechat or QQ] to [微信或QQ交流群]
2. Change Facebook and Twitter to Weibo and Wechat? I can provide

**Comment by leviding** [comment]
![image](https://user-images.githubusercontent.com/26959437/147055127-4f74305b-0ea0-4f83-8b1b-6b678988c903.png)

@iliakan I see that you have changed the link in homepage to Wechat 和 QQ.

Can we change the link in the image above as homepage?

**Comment by iliakan** [comment]
Oh, Chinese version has no discord, I'll remove this then.

**Comment by iliakan** [comment]
By the way, is discord forbidden in China?

**Comment by leviding** [comment]
@iliakan Discord is forbidden. For most Chinese, they use Wechat and QQ every. Only few people can use Discord or Telegram and so on (to talk some censored stuff).

I think we do not need remove it, we can change the copywriting to "我们创建了微信和QQ学习交流群，点击此处即可加入！". And when it is clicked, we popup this 👇
![image](https://user-images.githubusercontent.com/26959437/147056260-38223bbe-2894-4e9b-a29f-6e5f405ac3d5.png)

**Comment by iliakan** [comment]
This is a temporary notification about the new service. 

Sorry to hear it's not available in China.

**Comment by leviding** [comment]
> This is a temporary notification about the new service.
> 
> Sorry to hear it's not available in China.

@iliakan Get it. Some chinese can use Discord, so you can also do not remove it.
