### ISSUE TITLE
第二部分 UI事件--4指针事件描述错误

### ISSUE THREAD

**Issue by wanghongxuok** [javascript-tutorial/zh.javascript.info#986]
第二部分 UI事件--4指针事件中事件：pointercancel一节中阻止浏览器的默认行为来防止 pointercancel 触发。

我们需要做两件事：中的1的的第二条描述“这种方式也适用于鼠标事件”应改为“这种方式也适用于指针事件”

**Comment by songhn233** [comment]
“这种方式也适用于鼠标事件” 的意思是在这里通过设置 `ondragstart` 来阻止浏览器默认行为触发 pointercancel，同时对于鼠标事件这种方式也是有效的。
