### ISSUE TITLE
关于逻辑运算符缺少

### ISSUE THREAD

**Issue by morning-start** [javascript-tutorial/zh.javascript.info#997]
逻辑运算符缺少非短路的 & 和 |
Logical operators lack of not short-circuit & and |

**Comment by morning-start** [comment]
https://zh.javascript.info/logical-operators

**Comment by songhn233** [comment]
& 和 | 应该不归为逻辑运算符吧，属于 [位运算符](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators#binary_bitwise_operators)

**Comment by leviding** [comment]
> & 和 | 应该不归为逻辑运算符吧，属于 [位运算符](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators#binary_bitwise_operators)

是的
