### ISSUE TITLE
[ Variable scope, closure 变量作用域，闭包 ]这一章中的一个翻译问题

### ISSUE THREAD

**Issue by haigewang** [javascript-tutorial/zh.javascript.info#998]
英文原文 : In that case the Lexical Environment is still reachable even after the completion of the function, so it stays alive.
原译文: 在下面这个例子中，即使在函数执行完成后，词法环境仍然可达。因此，此嵌套函数仍然有效
建议译文：在下面这个例子中，即使在（外部）函数执行完成后，它的词法环境仍然可达。因此，此词法环境仍然有效。

**Comment by leviding** [comment]
Thanks. It has been improved in https://github.com/javascript-tutorial/zh.javascript.info/commit/e4e6eea429427c114e457efcf44475757c68b9d5

**Comment by haigewang** [comment]
thank you for your work!
